### ISSUE TITLE
Any way to remove +1? Also make dropdown not work?

### ISSUE THREAD

**Issue by micahblu** [bl00mber/react-phone-input-2#1]
I just need the phone input to work for US, though when adding onlyCountries={['us']} it still allows a dropdown of strange +\d's and the +1 in the input. Is there anyway to remove them? I don't mind the us flag I just don't need the dropdown values nor the +1 in the input

**Comment by bl00mber** [comment]
I added properties disableCountryCode and disableDropdown. Currently it is without formatting, so if you want you can add mask formatting for every country on strings 125, 413 in index.js file or I can add masks later.
