### ISSUE TITLE
onChange is not triggered in redux-form

### ISSUE THREAD

**Issue by RakhmatovR** [bl00mber/react-phone-input-2#10]
I wrapped this component into `redux-form` and passed `onBlur`, `onFocus` and `onChange` properties. First two are working but `onChange` doesn't trigger.

**Comment by douglaswissett** [comment]
A workaround I found for getting the value
is set a ref on ReactPhoneInput
```
  <ReactPhoneInput
    ref={(ref) => { this.phoneNumber = ref }}
    ...
```
then access the value using ref

`this.phoneNumber.state.formattedNumber`

Hope this issue gets fixed.
