### ISSUE TITLE
Change the country programmatically

### ISSUE THREAD

**Issue by TheLogan** [bl00mber/react-phone-input-2#101]
Hi, I have a dropdown on my site for setting the country of the user, and I'd like to use that value for the input field as well.
I've already disabled the inputs dropdown, but I can't figure out if there's any way to send the country code via code.
I've discovered that I can send the numbers (like value='45' for Denmark), but I'd like to send the country code as letters, so 'dk' rather than '45'. Is that possible?

**Comment by waynelei** [comment]
When switch countries, two way binding  fails. I have to downgrade to previous version 2.8.0

**Comment by bn0** [comment]
I might be misunderstanding your question, but this is how I set the country code dynamically:

**Comment by bl00mber** [comment]
Yes, country can be changed programmatically. You can check the example in demo.
