### ISSUE TITLE
country dropdown not visible

### ISSUE THREAD

**Issue by arunabhCronJ** [bl00mber/react-phone-input-2#107]
I've tried to implement the component into my project and am unable to see the country drop down.
The documentation doesn't say if any extra props are required to display the country dropdown.
I am implementing the component as below:

Formatting for the phone numbers works fine though.
Screenshot attached.
![Screenshot from 2019-06-08 17-35-53](https://user-images.githubusercontent.com/49940233/59147070-8a8d3600-8a14-11e9-9b85-0dbb867c3473.png)

**Comment by deridara** [comment]
Hi! Same issue. As I see, it depends on the containerClass prop, without this prop there is no additional div around input and dropdown button is visible

**Comment by saadiyakazi** [comment]
Hi, Facing same issue. Any updates? What properties should be passed to containerClass prop?

**Comment by alessandromontividiu03** [comment]
It worked for me after adding the css file
`import 'react-phone-input-2/dist/style.css'`

**Comment by sudhiryadav** [comment]
import 'react-phone-input-2/lib/style.css' in the App.js worked for me.

**Comment by ArtyomMedved** [comment]
Unable to resolve "react-phone-input-2/lib/style.css" from "App.js"
