### ISSUE TITLE
Search functionality is not working properly.

### ISSUE THREAD

**Issue by neelmshah** [bl00mber/react-phone-input-2#110]
Thanks for sharing this library it's great.

However, there is an issue in search functionality search result is not accurate. I have set "enableSearchField" as false. 

e.g.  If I'm typing "P" then it displays "Turkey" as highlighted item in the country list dropdown

Please refer to this video https://www.loom.com/share/fc799face1314e92adfe14a3f88b7273

Here is the code snippet.
![image](https://user-images.githubusercontent.com/50700060/59996262-80f00900-9677-11e9-977d-82bfd07300d0.png)

**Comment by dhruvrajkotia** [comment]
I'm facing similar issue as mention above. I set "enableSearchField" as false because when we set this value as a true then it display input box which I don't want in my component. So Is there any way to solve this issue?

**Comment by bl00mber** [comment]
You do not need to set `enableSearchField={false}`, it is false by default.
