### ISSUE TITLE
Can i customize the flag size?

### ISSUE THREAD

**Issue by waynelei** [bl00mber/react-phone-input-2#111]
Can i customize the flag size? i want to make the selected flag 120% larger

**Comment by MrFranke** [comment]
Flags set in CSS rules and image storage as base64. You can change CSS and set new flags Images
`.react-tel-input .flag` – selector for flags image.

**Comment by bl00mber** [comment]
SVG's can solve this, but it will require around ~500kb of weight. So I most likely will not add it.
