### ISSUE TITLE
Cant Remove + sign from react phone input 

### ISSUE THREAD

**Issue by Josh4you** [bl00mber/react-phone-input-2#114]
I want to remove "+" after I delete all react phone input. Refer Screenshots 
![Screenshot (24)](https://user-images.githubusercontent.com/32986210/60821757-c8bb7800-a1c1-11e9-9161-e95b0eedccb9.png)

This happens after I wipe off from the grid.
![Screenshot (25)](https://user-images.githubusercontent.com/32986210/60821758-c8bb7800-a1c1-11e9-88a3-206a4611a4f9.png)

**Comment by Wgil** [comment]
I also need this feature in order to allow optional phone numbers.

A workaround I'm currently using which is not so good because the `+` sign is still being shown but not stored:
```
<ReactPhoneInput
    value={value}
    onChange={phone => {
      if (phone === '+') {
        onChange('')
      } else {
        onChange(phone)
      }
    }}
/>
```

**Comment by wj-eurostar** [comment]
You could just choose to not render or hide the component when the input it empty.

**Comment by vjastik** [comment]
Please, add this functionality to package, because sometimes need to add optional field and it's so complicated with always on "+"

**Comment by meleshchenkoanastasiia** [comment]
@bl00mber and @razagill could I take this issue please?
