### ISSUE TITLE
Cant get correct dialcode in data.dialcode for some numbers like +1(585)5555555

### ISSUE THREAD

**Issue by karan-sah** [bl00mber/react-phone-input-2#117]
Not getting correct dialcode in data.dialcode for some numbers like +1(585)5555555,
getting data.dialCode as 1585 for the aove phone number, 
also for the number +1(225)9999999

**Comment by khippert5** [comment]
I am having this same issue. Area code should not effect the dial code. Area code should be held in a different value than dial code.

**Comment by bl00mber** [comment]
You should enable area codes to get full dialcode
