### ISSUE TITLE
Add option for custom classes

### ISSUE THREAD

**Issue by Alex-ray** [bl00mber/react-phone-input-2#12]
Currently the phone input has the options to set custom styles via the `inputStyle`, `buttonStyle` and the `dropdownStyle` optional properties.

A natural extension to this would be to enable custom classes via the `inputClass`, `buttonClass` and `dropdownClass` properties.

**Comment by Alex-ray** [comment]
I have a PR ready to go, but I don't have access to push branches up @bl00mber would you be up for giving me access so I can submit a PR for this feature request?

**Comment by Alex-ray** [comment]
PR ready to go

**Comment by arheinjohnson** [comment]
I can't seem to use dropdownClass successfully, can you provide an example on how to use it?
