### ISSUE TITLE
Release 2.9.5 not published on GitHub

### ISSUE THREAD

**Issue by serchavalos** [bl00mber/react-phone-input-2#121]
Hello 👋 

I noticed [the description on NPM](https://www.npmjs.com/package/react-phone-input-2) has the version 2.9.5 published but not this repo
<img src="https://user-images.githubusercontent.com/587388/63305500-77f37f00-c32a-11e9-9b17-b473306003d2.png" width="300px" />

Could you please upload these changes on GitHub too?

Cheers,

// Sergio

**Comment by bl00mber** [comment]
Why you have decided that it is not a 2.9.5 version in this repo?
