### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by rlyle** [bl00mber/react-phone-input-2#126]
Seeing an error currently..

lib.js:1782 Uncaught TypeError: Super expression must either be null or a function
    at lib.js:1782
    at lib.js:1781
    at Module.<anonymous> (lib.js:1320)
    at n (lib.js:14)
    at e.exports (lib.js:50)
    at Object.<anonymous> (lib.js:4)
    at f ((index):1)
    at Module.798 (EnhancedTableToolbar.js:88)
    at f ((index):1)
    at Object.425 (apricityTextLogo.png:1)

**Comment by sgehrman** [comment]
same issue here

**Comment by belonog** [comment]
have same issue

**Comment by leMedi** [comment]
same issue here.
happens when i build in prod mode (NODE_ENV=production)

**Comment by svn1991** [comment]
temporarily, you can use 2.9.3 version of this package till a new fix is released...hope this helps..:)

**Comment by mmcbruno** [comment]
same issue, downgrading to 2.9.3 solved it.

**Comment by LieeN** [comment]
Same issue here, can recommend using 2.9.5 as 2.9.3 was kinda outdated

**Comment by felipeaugusto1** [comment]
same issue here. and 2.9.3 is not working for me

**Comment by mankutila** [comment]
Same

**Comment by hachok** [comment]
as a workaround, you can add `keep_fnames: true` for a Terser plugin in Webpack configuration

**Comment by ayushnawani** [comment]
is it fixed? I am still getting this error

**Comment by LluisArevalo** [comment]
@bl00mber we have updated to the latest version of the package and it's still not working, here is the stack trace of the error (in production):

```
Uncaught TypeError: Super expression must either be null or a function
    at eval (lib.js:1782)
    at eval (lib.js:1791)
    at Module.eval (lib.js:1888)
    at n (lib.js:14)
    at e.exports (lib.js:52)
    at Object.eval (lib.js:53)
    at n (bootstrap:19)
    at Module.eval (phone-component.js:6)
    at n (bootstrap:19)
    at Object.eval (index.esm.js:100)
```

**Comment by ibrahim-ih** [comment]
to solve this problem temporarily build as dev
` "build": "webpack --config webpack.config.build.js --progress --mode development" `

**Comment by rb162215** [comment]
Same issue  Super expression must either be null or a function any solution.
I am using 2.9.4

**Comment by TedSean** [comment]
Using 2.10.0, this issue is still there

**Comment by anking** [comment]
Same issue comes up with _material-ui-phone-number_ that depends on this package

**Comment by abhijit-padhy** [comment]
I am still getting this error with latest version in production build `"react-phone-input-2": "^2.14.0",`. Following above comments I tried v2.9.3 which is also throwing same error for super expression.

It's terrific. I completed the whole implementation in local and when moved to prod it is throwing error. Now I am not sure why @bl00mber closed this ticket.

**Comment by abhijit-padhy** [comment]
Update: with v2.9.3 I'm not getting any error but I am not able to use 'react-phone-input-2/lib/style.css' and 'react-phone-input-2/lib/material.css' files used in v2.14.0.

**Comment by bl00mber** [comment]
@abhijit-padhy after I closed it there were no reports of this bug.
What is `libraryTarget` in your webpack config?

**Comment by abhijit-padhy** [comment]
@bl00mber  We haven't used `libraryTarget` in our webpack config.

**Comment by abhijit-padhy** [comment]
And when tried with `libraryTarget: 'commonjs2',` as I saw in your PR comment it breaks my application.
