### ISSUE TITLE
Cursor problems when typing

### ISSUE THREAD

**Issue by jquintozamora** [bl00mber/react-phone-input-2#128]
When put the cursor in the middle of a number and try to edit and then type a number. Then the cursor goes straight to the end and it should keep in the current position.

**Comment by Kevmue** [comment]
I can confirm the issue. I'm having the same problem. Seems to be related to https://github.com/facebook/react/issues/955

**Comment by bl00mber** [comment]
This is a feature. When country code is set by default, and user places a cursor to it, it jumps to the end so he doesn't need to move it to the end by himself and will not change country code accidentally.

**Comment by Shahul-H** [comment]
> This is a feature. When country code is set by default, and user places a cursor to it, it jumps to the end so he doesn't need to move it to the end by himself and will not change country code accidentally.

To handle this we have a prop called **countryCodeEditable**. I think you have misunderstood.
Try this scenario:
1. select country code.
2. Type numbers on input field. for example type(10 numbers).
Now you want to edit 4th and 5th numbers from the entered numbers
3. Place the cursor after 5th and 4th number and delete 4th and 5th number.
4. Now enter a new number. The cursor goes to the end after the first number is typed. 

This cause bad user experience.
