### ISSUE TITLE
Paste phone number in Safari 

### ISSUE THREAD

**Issue by noVVait** [bl00mber/react-phone-input-2#130]
When inserting a phone number in the Safari browser, the last digit of the number is cut off and you have to add it. This happens only in Safari, in other browsers everything works correctly.
![2019-09-30_1824](https://user-images.githubusercontent.com/35630425/65882951-8748fc00-e3af-11e9-9fe9-11d12a9e3ecf.png)
![2019-09-30_1824_001](https://user-images.githubusercontent.com/35630425/65882953-887a2900-e3af-11e9-9afe-e92eac6f08df.png)

**Comment by bl00mber** [comment]
Why it was closed?

**Comment by noVVait** [comment]
It was my mistake. Not yours

От: Nick Reiley
Отправлено: 30 сентября 2019 г. в 23:41
Кому: bl00mber/react-phone-input-2
Копия: Vadim; State change
Тема: Re: [bl00mber/react-phone-input-2] Paste phone number in Safari(#130)

Why it was closed?
