### ISSUE TITLE
Errors in IE11

### ISSUE THREAD

**Issue by noVVait** [bl00mber/react-phone-input-2#131]
Because of IE 11 doesn't support es6, includes functions and other es6 features don't work. Moreover, it crushes all site, when compiling the site in the ie 11. Can you fix it please (for example, replace all includes to indexOf)

**Comment by bl00mber** [comment]
Only includes or something else?

**Comment by noVVait** [comment]
I have lots of includes mistakes only
![image](https://user-images.githubusercontent.com/35630425/66016437-1d843b80-e4f0-11e9-8286-5720f8b0395f.png)
