### ISSUE TITLE
Not working with nextjs .

### ISSUE THREAD

**Issue by duongkhoangiam** [bl00mber/react-phone-input-2#132]
I am using react-phone-input-2 with nextjs https://nextjs.org/
when i running in dev mode is working. so when run build the page with react-phone-input-2 is not working and show error 
`An unexpected error has occurred.`

**Comment by bl00mber** [comment]
#131

**Comment by dulara1994** [comment]
I have also noticed this issue with nextJS version 9.1.1.
Browser shows the error message 
`An unexpected error has occurred.`
Browser console output is 
`TypeError: Super expression must either be null or a function`

**Comment by dydokamil** [comment]
#131 does not solve it

The error occurs with the production build only (next.js 9.1.1)

The error message is: 

> rollbar.min.js:2 Super expression must either be null or a function
TypeError: Super expression must either be null or a function

I can't take screenshots now, here's some code for context:

`}) || 0;
                    var m, g = h.length < 2 && s && !w()(h.replace(/\D/g, ""), s.dialCode) ? s.dialCode : "";
                    m = "" === h && 0 === s ? "" : n.formatNumber((e.disableCountryCode ? "" : g) + h.replace(/\D/g, ""), s.name ? s.format : void 0);
                    var y = a.findIndex(function(e) {
                        return e == s
                    });
                    return n.state = {
                        formattedNumber: m, // < this line
                        onlyCountries: u,
                        preferredCountries: f,
                        defaultCountry: e.defaultCountry,
                        selectedCountry: s,
                        highlightCountryIndex: y,
                        queryString: "",
                        showDropdown: !1,
                        freezeSelection: !1,
                        debouncedQueryStingSearcher: p()(n.searchCountry, 250),
                        searchValue: ""
                    },
                    n
                }
                var n, a;
                return function(e, t) {
                    throw new TypeError("Super expression must either be null or a function")
                }(),`

**Comment by efstathiosntonas** [comment]
Same here, next 9.1.3, only in production mode

**Comment by efstathiosntonas** [comment]
Everything is fine after the update, thanks

**Comment by willvlad** [comment]
Not working for me in production in nextjs. Fine in dev mode

**Comment by vstt2308** [comment]
> Same here, next 9.1.3, only in production mode

are you fixed ???

**Comment by vstt2308** [comment]
> Not working for me in production in nextjs. Fine in dev mode

help me , please !!!

**Comment by tutorhow** [comment]
It used to work in v2.10.1 but there were too many arbitrary data in country list, also the classes were also not applied... Broken again in 2.11.0
