### ISSUE TITLE
Search functionality doesnt work properly when using translations

### ISSUE THREAD

**Issue by ne0guille** [bl00mber/react-phone-input-2#133]
Ive the following configuration using localization with 'es', but the search input still search for the english value, for example if i search ESTADOS UNIDOS doesnt appear on the search result, but it does if i enter united states

```      <PhoneInput
        localization={es}
        enableSearchField={true}
        searchPlaceholder="Buscar"
        disableAreaCodes={true}
        defaultCountry={"es"}
        value={phone}
      />```

**Comment by bl00mber** [comment]
d17c06c4505388267aacf43b314f2e3f07a4eb7a
