### ISSUE TITLE
Country code editable and Afganistan Phone number Validations

### ISSUE THREAD

**Issue by mohanstriker03** [bl00mber/react-phone-input-2#134]
Hi, I have included countryCodeEditable prop as false, It works fine at the start but when input field contains any text, It will fail and we can edit country Code(i.e. +91, +354) etc. And for some countries, validations are not working properly. For example, Afghanistan.

**Comment by rajanrahman** [comment]
Hey, sorry for the unrelated note, but I wanted to know how you got validations to work? Having a tough time figuring it out. Really appreciate if you can help me out!

**Comment by mohanstriker03** [comment]
I think this library doesn't have a feature to do the validations for a Mobile number, I'm using **libphonenumber** library, you can learn more about this library in the mentioned link https://www.npmjs.com/package/libphonenumber-js

**Comment by bl00mber** [comment]
@rajanrahman you can validate using isValid(validator(phone))

**Comment by rajanrahman** [comment]
@bl00mber is there an example of this? I saw isValid={v => v === '1'} and was a little confused on how it worked. I'm trying to return the validity status to a parent component.

**Comment by bl00mber** [comment]
What's the point of confusion? The number will validate if condition is true.

**Comment by rajanrahman** [comment]
@bl00mber  So in my program I want to have a popup that lets the user know if the number was valid or not. I confused on what to send to my pop up handler from the phone input component

**Comment by bl00mber** [comment]
@rajanrahman its related to your application design, not to this plugin
