### ISSUE TITLE
countryCodeEditable can be circumvented

### ISSUE THREAD

**Issue by TheLogan** [bl00mber/react-phone-input-2#135]
I have countryCodeEditable set to true in my code, and in many ways it works, however I I just discovered way to still edit the country code.

Say you have "+45 12 31 23 23"
Either the 4 or 5 can be edited if you select it and then press a number button, at the same time you can also place the caret (text cursor) in front of it and press a number button.

I've tested this in both Chrome and Firefox

This is my code
<PhoneInput
            defaultCountry={this.getPhoneCountryCode()}
            value={this.state.MobilePhone}
            onChange={(val: any) => this.setState({ MobilePhone: val })}
            disableDropdown
            countryCodeEditable={false}
          />

**Comment by Dulajdeshan** [comment]
I'm also having this issue. 
![image](https://user-images.githubusercontent.com/38158937/67690855-a6917400-f9c3-11e9-9319-67252c5c2a85.png)

<PhoneInput
defaultCountry="au"
value={this.state.tp}
onChange={(val: any) => this.setState({ tp: val })}
disableDropdown
countryCodeEditable={false}
/>

The default Australia country code is +61. But it can be changed by placing the cursor infront of the + charactor.
