### ISSUE TITLE
Add more high resolution country icon

### ISSUE THREAD

**Issue by devhyunjae** [bl00mber/react-phone-input-2#138]
<img width="661" alt="Screen Shot 2019-10-30 at 11 40 58 AM" src="https://user-images.githubusercontent.com/12890257/67824611-38a39480-fb0a-11e9-8d93-cb5e5b3b18a8.png">

![120](https://user-images.githubusercontent.com/12890257/67824986-4c032f80-fb0b-11e9-9028-c39c090f55db.gif)

customized the input to be bigger.
but i can't size up the country icon :(
any quick fix tips?

**Comment by dizefurkan** [comment]
It's css sprite images... so you can't change the width or height... 
But you can fix by yourself:
Create a new high resolution image better than that after create sprite css for like (css properties: background-position) that's it.
