### ISSUE TITLE
counytry code doesn't update when you change the flag in two linked phone inputs

### ISSUE THREAD

**Issue by maxwaiyaki** [bl00mber/react-phone-input-2#139]
I have two linked phone number inputs `contact phone number ` and `Confirm your Mobile Payment`. When a user changes the country code on one, the country code on the other doesn't change rather the country code of the first gets appended and phone number value in the second. 

![max](https://user-images.githubusercontent.com/28390298/67877129-10d42100-fb4a-11e9-8e5b-1792532f60ca.png)

**Comment by oferpaster** [comment]
that happens to me too, I try to downgrade but no luck....

**Comment by bl00mber** [comment]
I dont understand what this sentence is about

> When a user changes the country code on one, the country code on the other doesn't change rather the country code of the first gets appended and phone number value in the second

When you change the flag on one input, second input will not update, because these are two different inputs. You can pass value to the input and change the country this way if your issue is about that.
