### ISSUE TITLE
Error when trying to use validation

### ISSUE THREAD

**Issue by hadimoha** [bl00mber/react-phone-input-2#148]
I'm trying to use the validation prop but I get an error.

/src/components/customer/PhoneField.js
  Line 37:24:  'startsWith' is not defined  no-undef
  Line 37:69:  'startsWith' is not defined  no-undef
![validate-error](https://user-images.githubusercontent.com/23414844/70389730-433c2e00-19d4-11ea-8b63-81fe49fa6a4b.png)

``<PhoneInput country={'ke'} 
        value={this.state.phone} onChange={this.handleOnChange} disableCountryCode={true} [placeholder={"0700000000"}](autoFormat={false}
 isValid={(inputNumber, onlyCountries) => {
              return onlyCountries.some((country) => {
                return startsWith(inputNumber, country.dialCode) || startsWith(country.dialCode, inputNumber);
              });
            }} />``

**Comment by bl00mber** [comment]
This error is in your app. The description of the cause is on your debug screen.
