### ISSUE TITLE
Update 2.10.0 -> 2.11.0 has breaking changes

### ISSUE THREAD

**Issue by Crawleyprint** [bl00mber/react-phone-input-2#149]
First - thanks for an excellent plugin, it's one of the best I've seen so far! 

Just a heads up in case nobody reported - new release broke our CSS (renamed classes) and some JS (renamed props).

It's nothing too large but it's unpleasant anyway.

**Comment by MyElectricSheep** [comment]
Hello ! Same here, wish to thank you for your work on this, it really is a great plugin :)

However, had the same issue as @Crawleyprint with the latest update; there are some breaking changes that prevented us from loading correctly the CSS and thus kept breaking the build.

`import 'react-phone-input-2/lib/style.css'`

During build, the CSS could not be loaded with a  'Cannot find module' error.

For those with the same issue that don't want to update to 2.11 right now; force your react-phone-input-2 version to version 2.10
`"react-phone-input-2": "2.10.0"`

Cheers !

**Comment by bl00mber** [comment]
@MyElectricSheep 
> During build, the CSS could not be loaded with a 'Cannot find module' error

This error cannot happen if you changed css import string to that you specified above.
