### ISSUE TITLE
ReactPhoneInput do not honour disableAreaCodes prop if prefferedCountryList passed

### ISSUE THREAD

**Issue by vivek-talentica** [bl00mber/react-phone-input-2#15]
When prefferedCountryList is passed to ReactPhoneInput, it shows list for codes for different areas of countries(like US, Canada), Even though disableAreaCodes prop is passed as true.

I have fixed this issue by passing filteredCountries to filter(To calculate preferredCountries list) instead of countryData.allCountries

Can you please incorporate this change in library as well

**Comment by bl00mber** [comment]
Thanks! I'll add fix within next days.
