### ISSUE TITLE
An issue with input mask behavior

### ISSUE THREAD

**Issue by AntonDmitrievich** [bl00mber/react-phone-input-2#150]
Hello,

I've found a strange behavior of the input mask

When a user enters the phone number and tries to update the entered data it moves each symbol to the right instead of updating the current symbol and changing the focus onto the next symbol.

Steps to reproduce:
1. Enter Ukraine phone number 38 012 345 67 89
2. Move focus on the '1' symbol
3. Type the same number 1 then 2,3,4,5,6,7,8,9

Expected that the entered number will be the same as it was
Actually it shows 38 012 567 98 43

You can check the videos 
[https://wetransfer.com/downloads/f8499d8a6b42bd94f422691165e6cb5120191210111426/d2495d](https://wetransfer.com/downloads/f8499d8a6b42bd94f422691165e6cb5120191210111426/d2495d)

**Comment by bl00mber** [comment]
#170
