### ISSUE TITLE
Drop down menu styles broken

### ISSUE THREAD

**Issue by n8sabes** [bl00mber/react-phone-input-2#151]
The drop-down country list is not rendering correctly in a React (hooks-based) + TypeScript + Material UI project.

<img width="306" alt="Screen Shot 2019-12-12 at 5 28 17 AM" src="https://user-images.githubusercontent.com/10445528/70719903-b6c98e00-1ca7-11ea-89bf-4a72c62ccf72.png">

Using v2.11.0, doing the following:

```
import PhoneInput from "react-phone-input-2";
import "react-phone-input-2/lib/material.css"

...

<PhoneInput
    style={{fontSize: "16px"}}
    country={'us'}
    countries={['us', 'ca', 'mx']}
    value={phoneNumber}
    onChange={(phone: string) => setPhoneNumber(phone)}
/>

```

**Comment by n8sabes** [comment]
Adding color to the style field (override) corrects the issue.

```
<PhoneInput
    style={{color: "black", fontSize: "16px"}}    country={'us'}
    countries={['us', 'ca', 'mx']}
    value={phoneNumber}
    onChange={(phone: string) => setPhoneNumber(phone)}
/>
```

It remains unclear how to affect the phone number text field itself in TypeScript, however.

**Comment by bl00mber** [comment]
This should not be an issue. As you can see, the [demo](https://bl00mber.github.io/react-phone-input-2.html) works without bug that you specified.
