### ISSUE TITLE
How to apply default mask, remove hyphen, to all the countries

### ISSUE THREAD

**Issue by divrt-srinath** [bl00mber/react-phone-input-2#154]
Would like to remove `-` from the mask for all the countries, trying to achieve it thru `defaultMask` but it does not work. Any example would be appreciated

> <ReactPhoneInput
                                defaultCountry='in'
                                onlyCountries={['in', 'at', 'gr', 'us']}
                                defaultMask=".. (...) .. .. .."
                              />

**Comment by bl00mber** [comment]
There is no hyphen in the masks

**Comment by divrt-srinath** [comment]
You can see hyphen in the below image I attached.

![image](https://user-images.githubusercontent.com/54371445/70981569-686b2380-20db-11ea-87ef-bda54496cb38.png)

I am expecting the format like the below image for all the countries. Its there in your examples, it would be great if you provide the source code.
![image](https://user-images.githubusercontent.com/54371445/70981703-a7997480-20db-11ea-9a1f-56d2af1ae096.png)

**Comment by bl00mber** [comment]
Currently plugin have no such functionality, probably will add in the future. For now you can only set masks for countries using `masks` and `defaultMask` props
