### ISSUE TITLE
Only constructor initial state value is considered if state bound to value changed later won't reflect

### ISSUE THREAD

**Issue by ssshet704** [bl00mber/react-phone-input-2#155]
Only constructor initial state value is considered if state bound to value changed later won't reflect.

could not set initial value

**Comment by bl00mber** [comment]
It's not correct, the value updated [here](https://github.com/bl00mber/react-phone-input-2/blob/b55da35b83c75ed238e86d0385e01f3cb3743bba/src/index.js#L205)
