### ISSUE TITLE
component has 'phone-form-control' as id on the input field which makes it non semantic when multiple are used

### ISSUE THREAD

**Issue by J-theGit** [bl00mber/react-phone-input-2#157]
Hi,
Thank you for this cool component.
I've noticed that I'm getting a lot of warnings on react app and they all come from using this input component.
Apparently the input of the phone field is using a hard-coded 'phone-form-control'. This means that whenever there are multiple of those on the page, there will be warnings shown in the console. Also, semantically this would be deemed as invalid HTML.
Would you be able to change the usage from id to a class? Or implement the fix for same id's in any other way?

Thank you

**Comment by rich186** [comment]
Also getting this! Whilst not critical, would be great to see a fix.
