### ISSUE TITLE
Flags are not displayed correctly when using Material-UI or Bootstrap CSS

### ISSUE THREAD

**Issue by Leminur** [bl00mber/react-phone-input-2#160]
I have got a problem with the flags whereas they are not exactly cropped correctly and other country flags are partially shown as picture below shows:

![chrome_9gkjHhoDXF](https://user-images.githubusercontent.com/9650859/71592594-9acf4480-2b0f-11ea-9eed-aa5c87ebf25e.png)

This is how I have implemented the Phone Input component. (I use the Material-UI Grid component. However, this flag glitch occurs no matter what, even when I am exporting the Phone Input Component alone).

```
<Grid item xs={4} sm={4}>
   <PhoneInput
         country={"mc"}
         value={inputPhone}
         onChange={phone => handleChangePhone(phone)}
         inputStyle={{ width: "100%" }}
   />
</Grid>
```

I have found the class that adjusts the size and crop for those flags (.react-tel-input .flag) and I have checked that it overrides the class that fixes that glitch (.flag) but I am not able to fix it. I have tried to use Material-UI's "makeStyles" and Default Module CSS to fix that problem but I did not manage to do so. (Any tips to do so would be appreciated!)

![chrome_Tq86KPOAkx](https://user-images.githubusercontent.com/9650859/71592988-f64e0200-2b10-11ea-9c1f-6dcc482af53d.png)

I do appreciate the time and the help given to solve this problem!

**Comment by tmurph21** [comment]
You can try to use `!important` on your overrides

**Comment by mahedihs1997** [comment]
I have had the same problem. It seems that the background image contains all countries. Only solution I found is to scale the flag up `transform: scale(2)` 😭

**Comment by shy-n** [comment]
Hi, fyi I had this problem and turned out to be the Authy client messing up with the flag dropdown selector.

**Comment by bl00mber** [comment]
Looks like not a bug in component itself.

**Comment by aroeshink** [comment]
I have this same issue. The default `plain.css` is being pulled in (it's the only css module that has those styles for the .flag class, and while this would be fine whenever the `material.css` module is imported, the background-image property is tagged as "!important"

I believe the package will function exactly the same without that !important flag
