### ISSUE TITLE
Spaces in the input mask trip up the autoformatter

### ISSUE THREAD

**Issue by xanderberkein** [bl00mber/react-phone-input-2#167]
When autoFormat is enabled, the input mask is not behaving as expected. The spaces trip up the formatter.

I created a gif to better illustrate the problem:

![Kapture 2020-01-20 at 16 04 55](https://user-images.githubusercontent.com/10937632/72737118-38fa7b80-3b9f-11ea-9a84-9439fca66f79.gif)

Here, I inserted the phone number `+32 000 00 00 00`. Then, I put the cursor before the first `0` and started typing `1` `2` `3` `4` `5` `6` `7` `8` `9`. 

I expect the end result to be `+32 123 45 67 89`, but instead I get `+32 123 56 89 74`.

**Comment by bl00mber** [comment]
This is related to **incorrect caret position calculation** #170
