### ISSUE TITLE
Clear input field on country select from the dropdown

### ISSUE THREAD

**Issue by TedSean** [bl00mber/react-phone-input-2#172]
Let say, I have filled the input field selecting India by default, now if i change the country from the dropdown let say to hongkong, can i clear the existing input field value cause it is sticking. @bl00mber 

![3nn9tt](https://user-images.githubusercontent.com/16174144/73446055-1415bd80-4382-11ea-8163-abe2efadcd56.gif)

**Comment by bl00mber** [comment]
#175
