### ISSUE TITLE
There is no way to fully clear the input

### ISSUE THREAD

**Issue by Volekss** [bl00mber/react-phone-input-2#175]
I made the phone number field optional in my project. But is there a way to fully clear the input after starting entering the phone number? Because I can't remove the country code if it was already selected.

**Comment by bl00mber** [comment]
You **can** remove the country code, you can't remove the prefix. The functionality to hide prefix (default behavior without option) if input is clear would be good to see. But to change default behavior when guessed country flag is sticking to input is not desirable. You may want **to add the possibility to pass -1 as the country value**, and if the condition is met, clear the country value when the input is empty.

**Comment by azmatrana** [comment]
Same issue, in my project phone field is optional as well but the inputs field is having a default value + as a prefix. Still looking for a way to clear the input.
![image](https://user-images.githubusercontent.com/8510334/75675568-35cbd280-5ca9-11ea-91b4-853b8091532f.png)

**Comment by bl00mber** [comment]
If you pass `null` as value, the country will be cleared.
If you pass empty string, country will not be cleared.

**Comment by praneethEnphase** [comment]
> Same issue, in my project phone field is optional as well but the inputs field is having a default value + as a prefix. Still looking for a way to clear the input. ![image](https://user-images.githubusercontent.com/8510334/75675568-35cbd280-5ca9-11ea-91b4-853b8091532f.png)

@azmatrana Were you able to find any solution to this? I do `Command + a` and then `Backspace`, it leaves a `+`. It's not clearing the entire input.

**Comment by leejanmorado** [comment]
@praneethEnphase I tried the ff and it clears the plus sign in the input:

```
onChange={(val, data, e, fmtVal) => {
  onChange(fmtVal === '' || fmtVal === '+' ? null : fmtVal);
}}
```
The inner onChange function is just a passed handler. The outer `onChange` function is the one needed for this library.
