### ISSUE TITLE
disable country autofit

### ISSUE THREAD

**Issue by vsolanogo** [bl00mber/react-phone-input-2#177]
for Dominican Republic +1809... it auto fits USA, how to disable it? I tried to manually set dominican republic and after it reset phone number - it fits USA anyway

**Comment by bl00mber** [comment]
Use `priority={{do: 0, us: 1, ca: 2}}`

**Comment by vsolanogo** [comment]
> Use `priority={{do: 0, us: 1, ca: 2}}`

doesn't work
