### ISSUE TITLE
cannot set required tabindex

### ISSUE THREAD

**Issue by J-theGit** [bl00mber/react-phone-input-2#178]
Hi,
I cannot set tabindex for this component as it's hardcoded for tabindex=0. 
Can you please make it possible to set it from props?

**Comment by naveennazimudeen** [comment]
@bl00mber Shouldn't the tabindex be set on the input element. Its now being set in the input element. In my code I had to use javascript to remove the tabindex from the div and add to the input to get the tabs to function correctly.

```
    const phoneInput = document.getElementsByTagName('input')[0]
    phoneInput.nextSibling.removeAttribute('tabindex')
    phoneInput.setAttribute('tabindex', '1')
```
