### ISSUE TITLE
Country dropdown does not navigate lineally

### ISSUE THREAD

**Issue by ravinpatel** [bl00mber/react-phone-input-2#179]
As I navigate down with the arrow keys, the highlighted area disappears, then when I continue to press down it highlights an area which is only half in shot, then the top selection is highlighted. 

![dropdown_issue](https://user-images.githubusercontent.com/14273533/75026863-90895100-5495-11ea-8fcc-5d1c6db4fb8d.png)

**Comment by bl00mber** [comment]
That's because you've changed the styles. You need to adjust your styles accordingly to the dimensions of the dropdown. As you can see in the demo, the input without style modifications has proper scroll.
