### ISSUE TITLE
Numbers hidden behind the flag dropdown

### ISSUE THREAD

**Issue by NikhilPunwaney** [bl00mber/react-phone-input-2#18]
![screen shot 2018-06-05 at 4 41 04 pm](https://user-images.githubusercontent.com/9063012/41001564-4ece38d2-68df-11e8-886b-8b05f98f97c0.png)

How can I make sure it's viewable?

**Comment by ddrgis** [comment]
You need to set left margin/padding to input styles

**Comment by spyshower** [comment]
Any real solution?

**Comment by bl00mber** [comment]
The 2nd comment suggested you a solution.
