### ISSUE TITLE
[BUG] Setting disableDropdown to true doesn't prevent keyboard actions 

### ISSUE THREAD

**Issue by ramyma** [bl00mber/react-phone-input-2#180]
Setting `disableDropdown` prop to `true` and pressing tab to the flag dropdown has 2 issues:

1. Flag drop down is highlighted when hovered
2. Pressing Enter while the drop down is highlighted displays the country list

Also pressing enter while the input is active should trigger the form submit, but currently the event doesn't bubble through.

**Comment by tmurph21** [comment]
This was closed yesterday.

#165
