### ISSUE TITLE
Label for input

### ISSUE THREAD

**Issue by Dima-Dim** [bl00mber/react-phone-input-2#181]
What about label for input? Or at least be able to use children for this purpose.

**Comment by vdineva** [comment]
Looks like you can pass in id to the `<input />` element by using `inputProps`: 
https://github.com/bl00mber/react-phone-input-2/blob/509c9fcb44ed84cc9c62d63845d66d96fb94b958/src/index.js#L840

so in my case I was able to do 

` <label htmlFor="phone">Phone</label>`
 `<PhoneInput inputProps={{ id: 'phone' }} />`

Hope this helps
