### ISSUE TITLE
Required:true not passing through inputProps

### ISSUE THREAD

**Issue by jowen19o** [bl00mber/react-phone-input-2#184]
<ReactPhoneInput
                        inputProps={{required: true}}
                        country={'us'}
                        inputStyle={{'width': '100%', 'border': '1px solid #ebebeb'}}
                        value={app.phone}
                        onChange={(e) => setApp({...app, phone: e})}
                        />

**Comment by jowen19o** [comment]
When submitting a form, 'please fill out this input' flag is not thrown.

**Comment by ted-hanson** [comment]
on "react-phone-input-2": "^2.12.0" this is definitely working for us

**Comment by jowen19o** [comment]
Finding this same issue on another project and using "react-phone-input-2": "^2.13.7"
