### ISSUE TITLE
Switching to a different country causing the phone number value to lose the + sign

### ISSUE THREAD

**Issue by apan0608** [bl00mber/react-phone-input-2#185]
If I type the numbers in, the value assigned to the phone value is correct, like +1 111 111
However if I change the country code from the dropdown list, without editing the phone  number, say the country code is +54, value I got become 54 111 111. I lose the + sign. 
If I edit it again, the + sign come back.

In this case I had to manually put the + sign back in which is ugly.

**Comment by yrbn** [comment]
same case

**Comment by leenakhaled** [comment]
@yrbn  @apan0608  same case , Any solution ??

**Comment by fleetofthemalden** [comment]
It causes the number to lose all of its formatting. Having this issue as well. 

Anyone looking into this? I might take a stab at it if not

**Comment by fleetofthemalden** [comment]
> @yrbn @apan0608 same case , Any solution ??

[This](https://github.com/bl00mber/react-phone-input-2/pull/205) should work @bl00mber

**Comment by bl00mber** [comment]
I cannot reproduce this. Can you provide a code example?

**Comment by borzecki** [comment]
I'm having the same issue. Because of it the library used for validating numbers is returning errors.

**Comment by fleetofthemalden** [comment]
> I cannot reproduce this. Can you provide a code example?

To reproduce 
```
const onChangeHandler = (phone, country, e) => {
   console.log({ phone, e })
}
...
someRenderMethod() {
   return (
      <>
         <PhoneInput
            {...variousProps}
            onChange={onChangeHandler}
         />
      </>
   )
}
```

Scenario 1) User enters text into input
> console log prints formatted phone number and defined event object

Scenario 2) User clicks the a different country via the flag input
> console log prints unformatted phone number and event object is undefined

**Comment by bl00mber** [comment]
@fleetofthemalden so plus sign is not lost in input, only in returned value?

**Comment by SanskarSans** [comment]
![image](https://i.imgur.com/eTVqmT0.png)

in my case, when i input phone number myself the + sign is lost anytime but if i provide initial value as "+9779812282124" then the value returns the same number without + sign being lost. 

Did i miss any props to support + sign for the returned value?

**Comment by fabienpatou** [comment]
> ![image](https://camo.githubusercontent.com/1d3811a4d582501b4f64b7dfdc6f29e8edf0505d/68747470733a2f2f692e696d6775722e636f6d2f655456716d54302e706e67)
> 
> @bl00mber in my case, when i input phone number myself the + sign is lost anytime but if i provide initial value as "+9779812282124" then the value returns the same number without + sign being lost.
> 
> Did i miss any props to support + sign for the returned value?

same here :)

**Comment by bl00mber** [comment]
I do not understand. You need to provide clear steps what needs to be done to lose the + sign, and the library version on which you lose it. If you do not have + sign on the 1st onChange argument it is expected behavior. The value which is provided as the first argument in onChange callback is unformatted. To get formatted value you should access 4th argument. This behavior must work from 2.13.x versions.
