### ISSUE TITLE
Rerender of component doesn't happen

### ISSUE THREAD

**Issue by Chingachcook** [bl00mber/react-phone-input-2#194]
When I fetch some info from server and try to setState phone to value props of <PhoneInput/>, it doesn't rerender and nothing happens.
I get from another component prop, that came asynchronously. By componentDidUpdate get latest prop value of phone and set it to state.
`componentDidUpdate(prevProps: InternationalPhoneInputProps) {
        if (this.props.phone !== prevProps.phone) {
            this.setState({
                phoneNumber: this.props.phone
            });
        }
    }
`

then from the state, I send it to <PhoneInput/>

`<PhoneInput
                    preferredCountries={ ['kz', 'ru'] }
                    country='kz'
                    **value={ phone }**
                    disabled={ isDisabled }
                    onChange={ (phone) => onPhoneChange(phone.replace(/\D/g, '')) }
                    copyNumbersOnly={ true }
                    placeholder={ placeholder }
                    inputProps={ {
                        name: 'phone',
                        required: isRequired,
                        autoFocus: isAutoFocused
                    } }
                    localization={ getCountryLocalization() }
                    masks={ {kz: '+. (...) ...-..-..', ru: '+. ... ... .. ..'} }
                    areaCodes={ {kz: ['7']} }
                />
                {   isAutoFocused && errorMessage && (
                    <div className="international-phone-input__message">{ errorMessage }</div>
                ) }`

in the react highlight extension in chrome I see that prop of component changed, but not of input inside the component

<img width="736" alt="Screen Shot 2020-03-17 at 18 07 44" src="https://user-images.githubusercontent.com/17483618/76854995-618ab300-687a-11ea-9293-7b51d602adfb.png">
<img width="736" alt="Screen Shot 2020-03-17 at 18 09 15" src="https://user-images.githubusercontent.com/17483618/76855016-6ea7a200-687a-11ea-985f-73045d5f24fc.png">

From attachments, you can see that the value of input not changed, if the value to props came after some time.

Can you help me with this issue? Thank you.

**Comment by vdineva** [comment]
You're passing into `<PhoneInput value={phone}` and I think it may have to be `<PhoneInput value={state.phoneNumber}`

**Comment by Chingachcook** [comment]
> I tried replicating your case and it works for me.
> Looking at the code you posted you're passing into `<PhoneInput value={phone}` and I think it may have to be `<PhoneInput value={state.phoneNumber}` (unless you're assigning within the render method `state.phoneNumber` to a local `phone` variable)

Hello. I value from the state of course. I renamed the variable.

**Comment by Chingachcook** [comment]
As you see the value changing in component <PhoneInput/> from props, but not setting it to html5 <input/> value inside component.

**Comment by bl00mber** [comment]
I cannot understand anything here. Please create the **minimally reproducible example** (without excessive code) in an online code editor if you continue experiencing the issue.
