### ISSUE TITLE
Incorrect Mask for American Territories 

### ISSUE THREAD

**Issue by sedenardi** [bl00mber/react-phone-input-2#195]
Typically when you type in `1` and then an "area code" that designates an American territory (such as 684 for American Samoa, or 671 for Trinidad and Tobago), it correctly detects the country distinctly from the US. However, it sets the mask to `+.... ... ... ... ... ..`, which is both incorrect (all use the NAMP, same as the US) and more digits than allowed in an E164 number.

For example, when I type in `16848762349`, the input field shows `+1684 876 234 9`, when it should show `+1 (684) 876-2349`. This is incorrect, and misleading to users.

Furthermore, the country data object returned in the `onChange` callback returns

```
{
  name: "American Samoa",
  dialCode: "1684",
  countryCode: "as",
  format: "+.... ... ... ... ... ..",
}
```

making input validation by comparing the input length to the format length impossible.

It looks like it's just appending the `defaultMask` to countries that don't have a defined mask without taking into consideration the length of the mask. Passing in a blank string to `defaultMask` doesn't work, as it prevents being able to enter any digits after the `dialCode`. 

A potential solution would be to allow disabling the `defaultMask` for countries with no defined mask and just do normal E164 length validation.

**Comment by bl00mber** [comment]
Why this needed if there is autoFormat = false prop?

**Comment by bl00mber** [comment]
You can pass defaultMask with the needed length and validate phone by adding dialCode.length to defaultMask length

**Comment by bl00mber** [comment]
I reverted this change because it does not make sense. You can disable autoFormat or pass defaultMask with the needed length

**Comment by sedenardi** [comment]
You're right, this was my mistake in looking at the returned mask in `format` and thinking it would allow inputting numbers longer than 15 digits, but this doesn't seem to actually be the case in practice.
