### ISSUE TITLE
Code Isn't Updated With Latest Release To NPM

### ISSUE THREAD

**Issue by gillerg8** [bl00mber/react-phone-input-2#197]
Hi @bl00mber,

I added some code into the last release, however, I'm not seeing it reflected in the latest version of this release (2.12.1).

The lib.js file in the github repo has the updates:
![react-phone-input-2-repo](https://user-images.githubusercontent.com/7545331/77082895-159f5180-69d3-11ea-928a-68ea24c89c3a.png)

However, the lib.js file when downloading from NPM does not have any of the updates:
![react-phone-input-2-build](https://user-images.githubusercontent.com/7545331/77082983-2ea80280-69d3-11ea-859e-5095b0ed5ef4.png)

Do you know why this is happening? I was just hoping you could give me your take on why this is occurring...

Thanks!
Geoff

**Comment by bl00mber** [comment]
That's a shame. I need to add `prepare` script.
