### ISSUE TITLE
Using prop function with setState in isValid cause Warning

### ISSUE THREAD

**Issue by Dmitrijus1989** [bl00mber/react-phone-input-2#198]
<ReactPhoneInput2
      localization={() => {
        switch (i18n.language) {
          case 'lt':
            return lt;
            break;
          case 'de':
            return de;
            break;
          case 'en':
            return false;
            break;
        }
      }}
      country={'lt'}
      preferredCountries={['lt', 'uk', 'de']}
      inputStyle={{ width: '100%', height: '40px' }}
      value={!!props.value ? props.value : ''}
      onChange={phone => {
        if (phone.charAt(0) !== '+') {
          props.onChange('');
          props.isValid(false);
        } else {
          props.onChange(phone);
        }
      }}
      isValid={inputNumber => {
        if (inputNumber.length === 0) {
          return false;
        }
        const noSpaceNumber = inputNumber.replace(/\s/g, '');
        if (noSpaceNumber.startsWith('370')) {
          if (noSpaceNumber.length === 11) {
            props.isValid(true);
            return true;
          } else {
            props.isValid(false);
            return false;
          }
        } else {
          return true;
        }
      }}
    />

props.isValid uses this.setState

![image](https://user-images.githubusercontent.com/43607055/77181249-bd03ad80-6ad3-11ea-812c-940fb7d9d2b4.png)

Any ideas how to fix it ?

**Comment by bl00mber** [comment]
Why do you use `props.isValid(true);`?
