### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by amertak** [bl00mber/react-phone-input-2#2]
Hi, great input :)

However I have one issue. When trying to search for a country in the dropdown, I get the call stack exceeded error. Have you encounter it?

``
Uncaught RangeError: Maximum call stack size exceeded
at n.searchCountry (index.js:1)
at n.searchCountry (index.js:1)
...``

Thanks ;)

**Comment by bl00mber** [comment]
This was a refactoring issue.
