### ISSUE TITLE
Event Propogation is blocked

### ISSUE THREAD

**Issue by shra1dhar** [bl00mber/react-phone-input-2#202]
**Occurence**
I was using your phone component in a form. The form had an `onSubmit` listener attached to it. But when I press _Enter_ (while the focus is on phone component), the `onSubmit` isn't triggered.

**Cause**
Event is being stopped from being bubbling out.

**Conclusion**
I'd love to investigate and eventually raise a PR addressing this concern. Or if you know it right away, then perhaps you can fix it too. Whatever suits you

**Comment by vdineva** [comment]
I had the same problem and the way I solved it was by passing in a custom function to the component for the `onEnterKeyPress` property - which I had to dig around the code to find out about
`<PhoneInput onEnterKeyPress={() => /* invoke function passed from form and submit the form */ }`
Hope this helps

**Comment by vdineva** [comment]
And the way to address this within the library would be to remove the default function `onEnterKeyPress` from line [139](https://github.com/bl00mber/react-phone-input-2/blob/master/src/index.js#L139 ):
and modify line [654](https://github.com/bl00mber/react-phone-input-2/blob/master/src/index.js#L654) to be `if (this.props.onEnterKeyPress) this.props.onEnterKeyPress(e);`
This way if no `onEnterKeyPress` is specified the event should bubble up the DOM.

**Comment by fabienpatou** [comment]
Same issue here, I'll use your solution @vdineva, thanks !
This onEnterKeyPress method should be removed from code, or documented, to avoid such issues. :)
