### ISSUE TITLE
Container looses it's native class if adding custom classes

### ISSUE THREAD

**Issue by yrbn** [bl00mber/react-phone-input-2#203]
The native class `react-tel-input` disappears when I add my own class to container `containerClass={'myContainerClass'}` . And all the nested styles of container being crashed.

**Comment by fleetofthemalden** [comment]
Hi, I will refrain from commenting on whether or not this should or should not be intended behavior, but the simple way to get around this behavior is to pass both the native class and your custom class to the component `containerClass={'myContainerClass react-tel-input'}`

Hope this helps!

**Comment by yrbn** [comment]
> Hi, I will refrain from commenting on whether or not this should or should not be intended behavior, but the simple way to get around this behavior is to pass both the native class and your custom class to the component `containerClass={'myContainerClass react-tel-input'}`
> 
> Hope this helps!

Yes, I already solved it in this way. But it is a crutch and not the fix.

**Comment by Anton-SN** [comment]
https://stackoverflow.com/questions/59809814/unable-to-increase-sizeheight-width-of-react-phone-input-2/59810291#59810291?newreg=c60411d95d3446cc9da585e7393fa1b1
