### ISSUE TITLE
Dropdown is to contained

### ISSUE THREAD

**Issue by PaulPCIO** [bl00mber/react-phone-input-2#206]
The parent element of the dropdown has the same height as the input `react-tel-input`, which causes an overflow problem:

![image](https://user-images.githubusercontent.com/39598117/78374124-c3158600-75cb-11ea-90f9-e4472e7f09b6.png)

In the image, you can see the dropdown overflows my container but the container is not aware of its height because it thinks the height is that of `react-tel-input`

would it not be better to leverage something like popper.js to handle the dropdown?

**Comment by vdineva** [comment]
Looks like you can just set a higher z-index for the `ul.country-list` element (the default is 1) and you can do it either by passing in `dropdownStyle={{ zIndex: 100 }}` or in your css - `ul.country-list { z-index: 100 }`
Hope this helps

**Comment by bl00mber** [comment]
Adding of external libraries which will increase the size does not seem as a good idea to me.
As for the overflow, you can regulate the height of your container. There is no overflow, dropdown block is absolutely positioned. If it will not be the case the component will be too big in height when collapsed or will change overall height when opened / collapsed which is not css friendly behavior.
