### ISSUE TITLE
County code not getting detected when passing the value from state 

### ISSUE THREAD

**Issue by deveshlashkari** [bl00mber/react-phone-input-2#211]
Hey,
I am having a form and when I open it for edit, I pass the Contact number from the state in the value attribute. But the country code is not detecting automatically. If I go and press any key from keyboard then it gets detected. Anyone facing the same issue? And Please help me. I have pasted the code below for better understanding. Also I have attached a screenshot [Here](https://prnt.sc/s0gfmj)

**Phone input code -** 
` <PhoneInput`
                      `  country={this.props.match.params.id ? "" : "us"}`
                      `  value={`
                        `  this.state.data.countryCode + this.state.data.mobile`
                       ` }`
                      `  onChange={this.handlePhone}`
                      `  autoFormat={true}`
                       ` placeholder="Enter contact"`
                      `  inputClass={`
                        `  !this.state.isCountryValid ? "is-invalid" : ""`
                       ` }`
                     ` />`

**Comment by bl00mber** [comment]
You should debug your case yourself. You have unknown variables in your code which I am not able to predict (and they are not related to the plugin).

**Comment by smesko85** [comment]
> You should debug your case yourself. You have unknown variables in your code which I am not able to predict (and they are not related to the plugin).

Here is a sandbox to reproduce:
https://codesandbox.io/s/muddy-fire-thhpx?file=/src/App.js

When there is no country code set and then the value is set, the React Phone Input component correctly guesses the country, but it also keeps the country code. On subsequent state updates if the country is the same everything works OK.

There is definitely a bug there.

**Comment by j0nezz** [comment]
> Here is a sandbox to reproduce:
> https://codesandbox.io/s/muddy-fire-thhpx?file=/src/App.js

I'm currently experiencing an issue that might be related to the above mentioned. When updating a phone number via state, the prefix is shown twice if the country code changes.

![image](https://user-images.githubusercontent.com/12492528/80113073-1c952300-8582-11ea-8378-5a28f42ecc16.png)

You can reproduce it by pasting the number `41791234567` (swiss phone number) into the state of @smesko85's sandbox
