### ISSUE TITLE
Max Length check 15 is Invalid for some Phone numbers

### ISSUE THREAD

**Issue by jschimmoeller** [bl00mber/react-phone-input-2#216]
In your code you have a check that a phone number should not be > 15 
    // Does not exceed 15 digit phone number limit
    if (value.replace(/\D/g, '').length > 15) return;

however this is invalid for some phone numbers with country code.  Specifically, Tanzania who's format is +... ... ... ... ... ... .."

**Comment by denyskorovets** [comment]
Have the same issue. Even though some country code formats exceed 15 characters, it is impossible to enter number that is more than 15 characters of length.

**Comment by shoaib9121** [comment]
@denyskorovets I tried [this](https://github.com/bl00mber/react-phone-input-2/issues/354#issuecomment-1227001558) proposed solution and it worked like a charm for me.

```
enableLongNumbers={formatDigits > 15 ? formatDigits : false}
```
