### ISSUE TITLE
How to change Label with material style

### ISSUE THREAD

**Issue by choukat** [bl00mber/react-phone-input-2#218]
Hi, I am trying to change the floating label of the input box with material style. By default it is input Phone, and i am looking everywhere I dont know how to change it. I think it is easy and i am sure someone can help me :).

Thank's a lot.

**Comment by bl00mber** [comment]
You can assign any static string to it through the css selector. Probably will add a possibility to change it through props to assign dynamic values such as country name in the future.

**Comment by acumulus8** [comment]
What are you referring to 'css selector'? (Great project by the way!!!!)

**Comment by avishekjana** [comment]
I'm also facing the same problem, any update on this issue?

**Comment by andrucz** [comment]
You can do this:

```
.react-tel-input {
  .form-control {
    & + div:before {
      content: 'Mobile Number' !important;
    }
  }
}
```

**Comment by abinasp** [comment]
@andrucz the above css working?

**Comment by kalolad1** [comment]
+1 on this issue

**Comment by XxOsirisxX** [comment]
After importing

`import 'react-phone-input-2/lib/material.css';
`

I can't change the input label.

My input looks like that:

![image](https://user-images.githubusercontent.com/16097653/172258625-d9bf7931-9e8d-4c7f-bc1d-c341928a1570.png)

I ma,age to change the value using this trick (:

`
        const result = document.getElementsByClassName('special-label');
        result[0].innerHTML = 'TEST'
`

But come on, let's be serious and expose a label attribute please.

**Comment by XxOsirisxX** [comment]
Well, this is how I did:

1. Surround your Phone component with a div with an id:

`
<div id={name}>
  <PhoneInput
  ...
  />
</div
`
2. Replace dynamically the label name using this code:

`
useEffect(() => {
  const result = document.getElementById( name ).getElementsByClassName('special-label');
  result[0].innerHTML = 'YOUR_LABEL';
}, []);
`
