### ISSUE TITLE
Incorrect country detecting for KZ

### ISSUE THREAD

**Issue by danilsitnikov** [bl00mber/react-phone-input-2#221]
Hi! Ive faced with issue. I typed +77 and see Russia, but it Kazakhstan. Could you pls add check if +77 or +76 select Kazakhastan?

**Comment by mabsystems** [comment]
The same problem(

**Comment by bl00mber** [comment]
This is correct detecting, because RU has priority > than KZ
priority={{ca: 0, us: 1, kz: 0, ru: 1}}

**Comment by Kirito2299** [comment]
> This is correct detection, because RU has priority > than KZ priority={{ca: 0, us: 1, kz: 0, ru: 1}

Hi, just wanted a quick insight into how can I remove priority from CA and US flag, as i tried putting priority to 0 but for the first call it is still showing US flag on choosing Canada
