### ISSUE TITLE
Props countryCodeEditable not working with United State (us)

### ISSUE THREAD

**Issue by Bdragon93** [bl00mber/react-phone-input-2#222]
Hi, I have an issue when the country is `us` (United State) and I set countryCodeEditable is `false` like this:

```
 <PhoneInput country="us" countryCodeEditable={false} enableSearch />
```

But the country code can be removed and can not enter the new one. :(

![inputphone](https://user-images.githubusercontent.com/9484412/79978086-86052b00-84c9-11ea-97a6-d47372f3449a.gif)

Did I miss something?
Please help me take a look!
TIA

**Comment by andrushkodmytro** [comment]
This issue is for all countries which have 1 digit in country code.

**Comment by Bdragon93** [comment]
It did not happen in my other repo with v2.12.0, but this version is not support TS :|

**Comment by KApilBD** [comment]
The same issue is happening with my code, and it is leading the other issue as well.
Once I remove the country code it additionally adds country code twice.

**Comment by raphaelnoguier** [comment]
Same problem for me with US

**Comment by bl00mber** [comment]
Can you send a failing test?

**Comment by farizsofyan** [comment]
I also face this issue. This issue can be seen in the demo (https://bl00mber.github.io/react-phone-input-2.html) as well with this configuration `{"country":"us","countryCodeEditable": false}`

**Comment by MJSPollard** [comment]
I believe this could be a quick fix for the issue until a PR gets merged.
```
<PhoneInput
  country='us'
  placeholder="Enter your mobile phone number"
  value={input}
  onKeyDown={(e) => {
    if ((e.which === 8 || e.which === 46) && input.length <= 1) e.preventDefault();
  }}
  onChange={(value) => {
    setInput(value);
  }}
  countryCodeEditable={false}
/>
```

**Comment by zaidyahya** [comment]
Thank you for the above, it works. A permanent fix should be rolled out though, the prop is pretty useless since the fix is pretty much at work for all cases.
