### ISSUE TITLE
<PhoneInput/> Property 'localization' does not exist on type 'IntrinsicAttributes & PhoneInputProps & { children?: ReactNode; }'

### ISSUE THREAD

**Issue by pinguo-hufangyan** [bl00mber/react-phone-input-2#232]
I want to use localization , but it tell me a error
Type error: Type '{ country: string; value: string; onChange: (value: string) => void; onlyCountries: string[]; localization: { de: string; es: string; }; }' is not assignable to type 'IntrinsicAttributes & PhoneInputProps & { children?: ReactNode; }'.
  Property 'localization' does not exist on type 'IntrinsicAttributes & PhoneInputProps & { children?: ReactNode; }'.  TS2322

**Comment by novikov1337danil** [comment]
I have same issue (prefix, className, localization props doesnt exists)

**Comment by novikov1337danil** [comment]
This problem is observed in version 2.13.3. Version 2.11.0 is working fine
