### ISSUE TITLE
International formating

### ISSUE THREAD

**Issue by sadux** [bl00mber/react-phone-input-2#234]
Can you support international formating as we type in phone input?
Like as diferent mobile or landline numbers in Australia example: +61 (9) 444-555 and +61 (444) 555-666

**Comment by bl00mber** [comment]
The stretch of area code is already supported by enableAreaCodeStretch

**Comment by bl00mber** [comment]
An example needs to be added to readme.

**Comment by sadux** [comment]
I tried and this is not what i said.. I need just format International format recognition. Mobile or landline: if i type: area is working but mobile not like: +61 444 555 666
