### ISSUE TITLE
Flag icon blocking country name in dropdown menu

### ISSUE THREAD

**Issue by tcarolroll** [bl00mber/react-phone-input-2#238]
<img width="298" alt="Screenshot 2020-05-22 at 7 42 19 AM" src="https://user-images.githubusercontent.com/23654591/82616481-e1792480-9bff-11ea-8433-00314001a0a0.png">

How do i fix this?

**Comment by bl00mber** [comment]
The view that you have screenshotted is non-standard. In the [demo](https://bl00mber.github.io/react-phone-input-2.html) the problem that you are mentioned is not present
