### ISSUE TITLE
value update with setState causes exception

### ISSUE THREAD

**Issue by sirpy** [bl00mber/react-phone-input-2#24]
if i have
<PhoneInput value={this.state.x} onChange={phone => phone.length>10?this.setState({x:''})}>
When i type the phone and it reaches 11 i get an exception 
"TypeError: Cannot read property 'iso2' of undefined"
it seems to be coming from the getCountryData method

**Comment by bl00mber** [comment]
I can't reproduce, your code is incorrect.

**Comment by jhlabs** [comment]
I am facing the exact same error when picking a country. However, it does not appear at every try. Might be related to this issue https://github.com/jackocnr/intl-tel-input/issues/84.
