### ISSUE TITLE
onChange not working

### ISSUE THREAD

**Issue by EugeneKovalev** [bl00mber/react-phone-input-2#25]
Hi @bl00mber 
Even when I add this `onChange={console.log('debug text')}` nothing happens in console when I type numbers.
But when I make Mouse Right Click the event is triggered. I guess it's wrong behavior

UPD:
Also I'd like to mention pasting is not tracked by events either

**Comment by Asurare** [comment]
Hello @bl00mber,

I am having the same issue there. I am trying to call an onChange as folllow :

```
    handlePhone(phone) {
        console.log("PHONE: " + phone);
    }
(...)
                                <ReactPhoneInput
                                    name="phone"
                                    defaultCountry={'fr'}
                                    preferredCountries={['fr', 'en', 'de', 'es']}
                                    placeholder="+33 1 02 03 04 05"
                                    inputClass="phone"
                                    value={this.state.phone}
                                    onChange={this.handlePhone}
                                />
```

And nothing is shown.

**Comment by bl00mber** [comment]
Because console.log() is a default JS function and not binded to component context by itself. You should use arrow function for this.
