### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by Manimall** [bl00mber/react-phone-input-2#255]
![2020-06-19_13-56-38](https://user-images.githubusercontent.com/2580719/85125749-de8c4680-b234-11ea-9da4-bc2b3be8f88f.png)
![2020-06-19_13-55-58](https://user-images.githubusercontent.com/2580719/85125750-df24dd00-b234-11ea-9067-0c176a667e49.png)

**Comment by bl00mber** [comment]
#247
