### ISSUE TITLE
Not working click on DropDown when it's wrapped in <label> tag

### ISSUE THREAD

**Issue by Manimall** [bl00mber/react-phone-input-2#259]
https://codesandbox.io/s/react-phone-input2-label-click-bip4n?file=/src/App.js - 
i suggest a PR that solves that problem - https://github.com/bl00mber/react-phone-input-2/pull/258

**Comment by HurYur** [comment]
It works for me in the sandbox example, but not works in my project.
The project has the same structure of the elements as you showed, hope that will be merged soon :)

**Comment by bl00mber** [comment]
I have not tested the suggested fix, but merged it because I suppose instinctively that it may work :smiley:
Wish this update will not break anything else

**Comment by Manimall** [comment]
@bl00mber  it will not break any other functionality - i test it
