### ISSUE TITLE
Mask characters interrupt deletion using Backspace

### ISSUE THREAD

**Issue by EugeneKovalev** [bl00mber/react-phone-input-2#26]
Hi @bl00mber 
When I try to delete a phone number using a backspace button and a cursor meets a mask bracket then nothing happens and I can not continue deletion. I have to press a left arrow button to jump over the bracket. That's kinda not comfortable.

Example: + 1 **(**555**)** 333-4444

**Comment by bl00mber** [comment]
What browser do you use?

**Comment by EugeneKovalev** [comment]
@bl00mber Google Chrome

**Comment by eeeman1** [comment]
The problem still exists in all browsers

**Comment by bl00mber** [comment]
@eeeman1 in browsers that I use problem don't exists. I not use Chrome so I can't fix this problem if such problem exists. If you can, you are free to send PR and I'll merge PR if it will not break existing code.

**Comment by aretsystems** [comment]
I can confirm that in the latest version of google chrome this issue persists. 

Google Chrome
Version 72.0.3626.96 (Official Build) (64-bit)

**Comment by aretsystems** [comment]
> The problem still exists in all browsers

You may try [this](https://codesandbox.io/s/2j30qo8yy0?from-embed) example, instead of passing **onChange** as **inputExtraProps**, specify it's directly as in the sample demonstrates.
