### ISSUE TITLE
Question: how to change "search" text ?

### ISSUE THREAD

**Issue by Aarbel** [bl00mber/react-phone-input-2#261]
![image](https://user-images.githubusercontent.com/25119847/85419476-6db99700-b572-11ea-99f7-25e61dda87ea.png)

The "search" text doesn't seem to be modifiable, is there a way to change it ? Thanks a lot !

**Comment by Manimall** [comment]
@Aarbel 
![2020-06-23_18-15-49](https://user-images.githubusercontent.com/2580719/85421995-c3e00780-b57d-11ea-9108-d5258ab69682.png)

pls read the docs carefully
