### ISSUE TITLE
can't get focus of null

### ISSUE THREAD

**Issue by Manimall** [bl00mber/react-phone-input-2#262]
when i try to get my value using onChange fn - the console give me an error - 

`can't get focus of null` - or smth like that.
look at this - https://codesandbox.io/s/input-ref-sometimes-equals-null-zohui?file=/src/App.js - for details - 

so, how to fix - you should add an if statement to check if the ref exists in 2 places in index.js:

1) 
```js
// Put the cursor to the end of the input (usually after a focus event)
  cursorToEnd = () => {
    const input = this.numberInputRef;
    if (input) {
      input.focus();
      let len = input.value.length;
      if (input.value.charAt(len-1)=== ')') len = len-1;
      input.setSelectionRange(len, len);
    }
  }
```

2) in `render` method into a `return` statement:
```js
      <div
          className={flagViewClasses}
          style={this.props.buttonStyle}
          ref={el => {if (el) this.dropdownContainerRef = el}}
          tabIndex={disableDropdown ? '-1' : '0'}
          role='button'
        >
```

**Comment by GiancarlosIO** [comment]
@Manimall Have you found a solution for this? 😢

**Comment by Manimall** [comment]
> @Manimall Have you found a solution for this? 😢

this one was fixed - i made i PR solving this problem

**Comment by Manimall** [comment]
> @Manimall Have you found a solution for this? 😢

the main problem of the library is here - https://github.com/bl00mber/react-phone-input-2/issues/377

but you can use fourth argument in onChange fn - and create a wrapper component to aviod this problem - 

`const PhoneInputWrapper: FC<PhoneInputWrapperProps > = ({
  value,
  onChange,
  ...props
}) => {
  const [phoneValue, setPhoneValue] = useState(value);

  const handlePhoneChange = useCallback(
    (
      value: string,
      _data: Record<string, never>,
      _e: ChangeEvent<HTMLInputElement>,
      formattedValue: string,
    ) => {
      // saving and sending unformatted value to backend
      onChange(value);

      // changing the component state correctly
      setPhoneValue(formattedValue);
    }, []);

  return (
    <PhoneInput
      { ...props }
      value={phoneValue}
      onChange={handlePhoneChange} />
  );
};

export default PhoneInputWrapper;`
