### ISSUE TITLE
Constant flag switching between CA and USA.

### ISSUE THREAD

**Issue by AAlvarez90** [bl00mber/react-phone-input-2#287]
If you had two countries only: CA and USA.
And you select CA for the flag and start typing: 2 then 8, the flag will switch to USA, but when you finally type 9 to complete the area code, it switches back to Canada which is where it should have stayed.
I believe the problem is here:
https://github.com/bl00mber/react-phone-input-2/blob/master/src/index.js#L181
It tries to guess the country with only 2 numbers and in my opinion it should wait until it has 3 numbers to guess the country. Specially in the cases of USA and CA.

**Comment by jcamilomnavia** [comment]
I have the same problem with redux-form, when I change to Canada, it remains in the US flag, but when I type the Canada number it changes. is there a way/prop to disable the country guess so the Canada flag remains all the from the beginning?

**Comment by bl00mber** [comment]
Related to minimum 3 numbers: it is a very bad suggestion. This will cause a lot of unexpected bugs with different country code lenghts and it breaks even ca/us detection logic because component should identify country correctly and when it detects canada it is proper heuristics.
