### ISSUE TITLE
Getting Material-UI Style

### ISSUE THREAD

**Issue by il-frans** [bl00mber/react-phone-input-2#289]
Simple question which I can't seem to figure out, how the get the material UI look? I'm using material-ui through out my project only suing controls for that library apart from this control.

Doing these lines of code doesn't change the look, which makes me think I'm missing some prop?

import PhoneInput from 'react-phone-input-2'
import 'react-phone-input-2/lib/style.css'

<PhoneInput
  country={'us'}
  value={this.state.phone}
  onChange={phone => this.setState({ phone })}
/>

**Comment by JTambunt** [comment]
import 'react-phone-input-2/lib/material.css';

**Comment by il-frans** [comment]
Fantastic! That got me closer to what I need to achieve. Is there a way to change the variant? By Default it seems to be set to "Outlined", I would like to get the look and feel of the standard one as shown here https://material-ui.com/components/text-fields/

Any ideas?

**Comment by jasminnancy** [comment]
> Fantastic! That got me closer to what I need to achieve. Is there a way to change the variant? By Default it seems to be set to "Outlined", I would like to get the look and feel of the standard one as shown here https://material-ui.com/components/text-fields/
> 
> Any ideas?

Heres what I did :)

```
phoneInputClass: {
   '&+div:before': {
      content: "'' !important"
    }
}
```

```
<PhoneInput
	onChange={handlePhoneChange}
	inputClass={phoneInputClass}
	inputStyle={{
		width: 'inherit',
		border: 'none',
		borderBottom: 'solid #ececec 1px',
		padding: '0 14px 0 58px',
		borderRadius: '0'
	}}
/>
```

**Comment by il-frans** [comment]
> > Fantastic! That got me closer to what I need to achieve. Is there a way to change the variant? By Default it seems to be set to "Outlined", I would like to get the look and feel of the standard one as shown here https://material-ui.com/components/text-fields/
> > Any ideas?
> 
> Heres what I did :)
> 
> ```
> phoneInputClass: {
>    '&+div:before': {
>       content: "'' !important"
>    }
> }
> ```
> 
> ```
> <PhoneInput
>    onChange={handlePhoneChange}
>    inputClass={phoneInputClass}
>    inputStyle={{
>       width: 'inherit',
>       border: 'none',
>       borderBottom: 'solid #ececec 1px',
>       padding: '0 14px 0 58px',
>       borderRadius: '0'
>    }}
> />
> ```
> 
> <img alt="Screen Shot 2020-08-18 at 10 00 02 AM" width="284" src="https://user-images.githubusercontent.com/26612415/90522357-9b1d5e00-e139-11ea-895e-3f3eb5eb733a.png">

Fantastic! This is good enough for me, Thanks for the help to all who replied

**Comment by PunkFleet** [comment]
@jasminnancy  How to custom focus border style?

**Comment by PunkFleet** [comment]
@jasminnancy 
```
.phone_number.react-tel-input input:focus {
  border: 1px solid #673ab7 !important;
}

<PhoneInput      
            containerClass='phone_number'      
            inputStyle={{width: '100%' }}
            country={'us'}
        />
```
