### ISSUE TITLE
Country list order

### ISSUE THREAD

**Issue by appleneil** [bl00mber/react-phone-input-2#294]
The country list order is not updated according to the current locale. We load the french locale yet the countries are loaded in English alphabetical order. Is there a way around this?

**Comment by tlair001** [comment]
Hi,
In french locale, countries beginning with accents are placed at the end of the list.
Example: "États-unis" is placed at the end of the list instead of next to the countries beginning with the letter "E".
Is it possible to change this or to get around the problem?

Thanks !

**Comment by bl00mber** [comment]
Hi tlair001! Can you send a PR with the updated french locale?

**Comment by bl00mber** [comment]
Hi @tlair001! Can you send a PR with the updated french locale?

**Comment by bl00mber** [comment]
Seems like limitation of the native sort function. You can use `preserveOrder` to assign items in defined order.
