### ISSUE TITLE
PhoneInput requires 2 tabs to continue to next field

### ISSUE THREAD

**Issue by jtruzzi** [bl00mber/react-phone-input-2#299]
After filling the field, we need to press TAB two times to continue with the next field. 
If you click tab only once, the focus seems to go to a hidden element. 
Also If you press ENTER in this stage, a list of countries gets displayed.

![image](https://user-images.githubusercontent.com/6401468/90636956-bd7aae80-e201-11ea-8412-0f1ccb7d3a18.png)

![image](https://user-images.githubusercontent.com/6401468/90636972-c4092600-e201-11ea-81b5-ce1ba365d57f.png)

**Comment by jtruzzi** [comment]
nevermind, its a css issue.

**Comment by salvishahzadtrantor** [comment]
@jtruzzi what was the issue? I am facing the same problem
