### ISSUE TITLE
Customizable order of country codes

### ISSUE THREAD

**Issue by official-brodnikov** [bl00mber/react-phone-input-2#302]
For example, I would like to somehow send the list of countries to onlyCountries, and so that in the dropdown list they are displayed in the same order, and not in alphabetical order. Or for example, I use a combination of onlyCountries/preferredCountries and pass the list of countries that will be at the top to the country preference, which is cool, but they are also sorted alphabetically. It would be great to turn off alphabetical sorting on your side so that we can send the list in onlyCountries or preferredCountries in the order that is needed. Or make a flag, need to be ordered or not.

**Comment by bl00mber** [comment]
As written in readme, you should use preserveOrder. It does not sort the list alphabetically and its the only purpose of this property.

**Comment by official-brodnikov** [comment]
Oh man, no, you didn't understand me at all. It's not about preserveOrder.
Once again, I don't like that you form the list of country codes in
alphabetical order. I need to get a list of countries in the order i pass
you in onlyContries.

E.g. onlyContries=[“us”,  “ca”, “ru”]. I get from you in the code list:
Canada
Russia
United States of America

But I want to get:
United States of America
Canada
Russia

Also I meant prefferedContries
prefferedContries=[“us”,  “ca”, “ru”]

I want to get at the top of the list:
United States of America
Canada
Russia

Not:
Canada
Russia
United States of America

I understand that many do not care about the order of all countries,
because most often there are many, and alphabetical order is the best
solution.  But I think at the top of the list, many do not need an
alphabetical order, and personally to me.

I suggested adding a flag, alphabetSort = true, you sort, false leave the
order as you passed it in the list, please do at least for the
preserveOrder / preferredContries combination!

пн, 24 авг. 2020 г. в 22:39, Nick Reiley <notifications@github.com>:

**Comment by official-brodnikov** [comment]
OR
sort string “all” | “pref” | “not_pref” default_value=“all”

вт, 25 авг. 2020 г. в 18:02, Alexey B <brodnikov111@gmail.com>:

**Comment by bl00mber** [comment]
As I've said, preserveOrder allows you to to not sort alphabetically. I will not add flag alphabetSort, because preserveOrder does the same.

**Comment by bl00mber** [comment]
You can check out {"onlyCountries": ["us",  "ca", "ru"], "preserveOrder": ["onlyCountries"]} on [demo](https://bl00mber.github.io/react-phone-input-2.html)
