### ISSUE TITLE
British Indian Ocean Territory flag frequently shows up when it's not supposed to

### ISSUE THREAD

**Issue by jasminnancy** [bl00mber/react-phone-input-2#303]
Flag always defaults to "British Indian Ocean Territory" flag if `country={'us'}` is not set or if value is null.

1. Flag should show US flag if area code is set to `1`.
<img width="374" alt="Screen Shot 2020-08-24 at 9 18 56 AM" src="https://user-images.githubusercontent.com/26612415/91049221-d8c33080-e5ea-11ea-9c62-4ef1d2464f62.png">

2. Default flag should be able to be changed when value is null (placeholder is set to '---')
<img width="260" alt="Screen Shot 2020-08-24 at 9 22 12 AM" src="https://user-images.githubusercontent.com/26612415/91049580-6272fe00-e5eb-11ea-8d28-565cacb1e695.png">

**Comment by bl00mber** [comment]
This is not only territory with missing flag. There is a lot of territories without flag. It will be tracked here #182
