### ISSUE TITLE
Create release for PR #272

### ISSUE THREAD

**Issue by pedrofsantoscom** [bl00mber/react-phone-input-2#306]
Hello, 

Are you able to create a release version for this PR #272 or the last commit [2.13.8](https://github.com/bl00mber/react-phone-input-2/commit/a48b16ce79a5751a97ad6f76b000932aeaf1abf3)?

Thanks in advance!

**Comment by bl00mber** [comment]
It is released 2 days ago

**Comment by pedrofsantoscom** [comment]
@bl00mber I mean as a [release](https://github.com/bl00mber/react-phone-input-2/releases) or [tag](https://github.com/bl00mber/react-phone-input-2/releases) on github. Can you do it?
Thanks

**Comment by bl00mber** [comment]
Created
