### ISSUE TITLE
Incorrect Iran format

### ISSUE THREAD

**Issue by elnur0000** [bl00mber/react-phone-input-2#312]
Hi,
input for Iran only allows 13 characters, but I see there are 14 dots in the format 
![Capture](https://user-images.githubusercontent.com/35765747/92228241-9a662500-eeb8-11ea-9883-1b4fff511fed.PNG)
![Capture](https://user-images.githubusercontent.com/35765747/92228321-bff32e80-eeb8-11ea-99a5-5af2f1d39a91.PNG)

now I checked and seems like it's not only Iran, formats of most countries doesn't match :/

**Comment by bl00mber** [comment]
Those types of issues are [forbidden](https://github.com/bl00mber/react-phone-input-2#contributing)
