### ISSUE TITLE
How do I enter the country name in renderStringAsFlag?

### ISSUE THREAD

**Issue by siarheiSiniauski** [bl00mber/react-phone-input-2#317]
How do I enter the country name in renderStringAsFlag? Or is there some option to show the name of the country instead of the flag, Often you have to display a flag with the name of the country.

**Comment by bl00mber** [comment]
This is not a bug. Please consider filling a question on [stackoverflow.com](stackoverflow.com)

**Comment by rod-stuchi** [comment]
Hi @siarheiSiniauski  did you find something that allow disable the flags and show country code instead?

**Comment by h27-webdev** [comment]
@siarheiSiniauski @rod-stuchi Hi, were you able to figure this out?

**Comment by rod-stuchi** [comment]
@h27-webdev only by manipulating the DOM directly.
