### ISSUE TITLE
French Number starting with 0

### ISSUE THREAD

**Issue by Dono7** [bl00mber/react-phone-input-2#318]
Hello !
I am using the react-phone-input-2 component for a form on a french website :fr: :wave: . In france, numbers can have 2 formats : 
- `+33 x xx xx xx xx` (or) `+33xxxxxxxxx`
- `0x xx xx xx xx` (or) `0xxxxxxxxx`

(where x can be any number from 0 to 9)

For example, the following formats are valid french number :
- `+33 6 18 67 29 54` (or) `+33618672954`
- `06 18 67 29 54 (or) `0618672954`

But I cannot achieve to use the second format with this component, since the first format is the only one supported. I can only do something like `+0618672954` (which is not valid, because of the plus sign)

And sometimes, it even wicthes to another country. For example, `01 18 67 29 54` can be interpreted as `+1 186 729 54` (US or CA)

Could it be possible to "disable" the auto-format and country-guess when the first character is '0' ? I think their is no conflict with that ?
Is there any other possible solution to handle this format ? 

Thanks !

**Comment by bl00mber** [comment]
You probably can turn prefix off and on algorithmically in onChange callback depending on the value... personally I do not know. You can try to find out yourself or ask a question on stackoverflow. The primary use of issues section is for reporting issues and suggestions, not for consulting.
