### ISSUE TITLE
how i can get area code in onChange function

### ISSUE THREAD

**Issue by yashrajb** [bl00mber/react-phone-input-2#329]
how I can get the area in when the onChange function is called? in one of my application, we want to timezone on the basis of country code with area code
```
<PhoneInput
                            value={telNo}
                            enableAreaCodes={true}
                            onChange={this.props.onChangeTelNo}
                            enableAreaCodeStretch
                            areaCodes={{us: ['300']}}
                          />
```
any help is appreciated

**Comment by styfrombrest** [comment]
You should receive countryData object as second argument in onChange callback, then use countryCode and momentJS library to get what you need  :
![image](https://user-images.githubusercontent.com/6871536/95584053-5c22cf00-0a3d-11eb-9281-178f42dfc0ed.png)

**Comment by bl00mber** [comment]
Please read readme.md
