### ISSUE TITLE
Flexible mask

### ISSUE THREAD

**Issue by ochan12** [bl00mber/react-phone-input-2#333]
It would be great if the mask could be according the area codes of each country. Argentina for example has 3 different area code lengths according to each zone (yes, it's that bad). 
- Buenos Aires: +54 (11) 1234-5678
- Cordoba: +54 (351) 223-4769
- Ameghino: +54 (3388) 46-4037

So the idea would be that it takes the minimum length by default and if it has larger area codes check if its written at the beginning and use it.

**Comment by bl00mber** [comment]
This is already implemented with `enableAreaCodeStretch`. I will not close the issue because seems it is not clearly enough described in readme.
