### ISSUE TITLE
Invariant Violation: Text strings must be rendered within a <Text> component

### ISSUE THREAD

**Issue by sash6** [bl00mber/react-phone-input-2#334]
I'm getting this issue with just inserting PhoneInput tag. for more information look into the image
![iss-rn](https://user-images.githubusercontent.com/43516692/96027953-503c7000-0e76-11eb-8282-5507a1cd5b2f.JPG)

**Comment by bl00mber** [comment]
This is undebuggable & the issue is clearly in your app. If you copy the code that you presented into the clear app with react only this should work.
