### ISSUE TITLE
Styles are not applied when used with nextjs

### ISSUE THREAD

**Issue by jinxac** [bl00mber/react-phone-input-2#335]
Hi Folks,

I was using this package in my next-JS project.  I have made all the configuration for loading CSS in my project and it works fine with another import but with this library, I am facing issues.

I observed that the way next imports the CSS in the module file is as an object. This object has keys as the name of the classes mentioned in CSS files and value as a hash to the actual styles. 

So my assumption is that inside the phone input component we are reading actual strings as classNames('react-tel-input', 'flag-dropdown' etc...) and not the hash values which nextjs has actually created. 

Moreover, I am not even sure if this issue belongs to nextJS or this library, so this is more of a feedback/question.

Looking forward to your reply. Thanks.

**Comment by jinxac** [comment]
Looks like this is an issue with next, I created `_app.js` inside the pages directory and imported the `styles.css` file there. It works fine with that.

**Comment by nabiltkarim** [comment]
I tried your method by putting it in `_app.tsx`. However, its still not importing the styles. Any idea why?
