### ISSUE TITLE
Use with react-hook-form

### ISSUE THREAD

**Issue by ws-zykina** [bl00mber/react-phone-input-2#339]
If use  react-hook-form Controller and render method
`<Controller
            name="mobileNumber"
            control={control}
            render={({ onChange, value, name }) => (
              <PhoneInput
                country="us"
                onlyCountries={['us', 'mx', 'ca']}
                value={value}
                inputProps={{
                  name,
                }}
                onChange={(tel) => {
                  onChange(tel);
                }}
                specialLabel="Mobile Number*"
              />
            )}
          />`

onlyCountries={['us', 'mx', 'ca']}

If select Mexico and then select Canada - selected USA

**Comment by shettykaran21** [comment]
@ws-zykina Did you find a solution or a work around for this?
