### ISSUE TITLE
onChange don't work

### ISSUE THREAD

**Issue by eeeman1** [bl00mber/react-phone-input-2#34]
onChange don't work

`import ReactPhoneInput from 'react-phone-input-2';`

```
                    <ReactPhoneInput
                        defaultCountry={'ru'}
                        onChange={() => console.log('change')} //does not work!!!
                        onKeyDown={() => console.log('keyDown')} //work
                        onClick={() => console.log('click')} //work
                        onBlur={() => console.log('blur')} //work
                        onFocus={() => console.log('focus')} //work
                        value={this.state.value}
                    />
```
when entering a number, a callback does not work, all events except onChange work.

for comparison, if you use the react-phone-input, then onChange works

I ask urgently to solve the problem!

"react": "^15.5.4",
"react-phone-input-2": "^2.5.0",

**Comment by bl00mber** [comment]
Duplicate of #29

**Comment by eeeman1** [comment]
the problem is urgent, on entering numbers does not work onChange

**Comment by eeeman1** [comment]
as an example you can see this component - https://github.com/razagill/react-phone-input, everything works correctly here
