### ISSUE TITLE
Chrome autocomplete not working well

### ISSUE THREAD

**Issue by Lapro15** [bl00mber/react-phone-input-2#340]
Hello,
Following the integration of your lib, we noticed that the Chrome autocomplete does't work if the prefix linked to the country code is not entered in the saved number of the user.
For example, if my number saved in Chrome is `4185555555`, a Canadian number, where the prefix` 1` is missing, then autocomplete will only add `4185555555` and I will be located in Switzerland.
Wrong:
![image](https://user-images.githubusercontent.com/27449544/97753239-cde5ba00-1acb-11eb-96db-1e6a40413524.png)
vs
Right:
![image](https://user-images.githubusercontent.com/27449544/97753260-d5a55e80-1acb-11eb-9f75-3a71f436b343.png)

**Comment by bl00mber** [comment]
Of course the behavior intended by you will not work if the phone number do not have a canadian prefix — it will not have a way to determine the country that you want it to display.

**Comment by Anindya91** [comment]
I had the same issue, I got it to work with this workaround.

```
function handleChange(value, data, event, formattedValue) {
  if (value.length - val.length > 1 && value.length === 10) {
    setVal(`1${value}`);
  } else {
    setVal(value);
  }
}
  
<PhoneInput
  onChange={handleChange}
  ...
/>
```

**Comment by S-Vlad** [comment]
It is not relevant to the topic, but i want to save somewhere my solution. If autocomplete not working, then try to pass field name to inputProps like ```inputProps={{ name: 'phone' }}```

**Comment by calumptrck** [comment]
passing the `countryCodeEditable={true}` prop solves this issue for all regions

**Comment by tatetoussaint** [comment]
Is there a way to make it default to a certain country code if the phone number autofilled is 10 digits?
