### ISSUE TITLE
React does not recognize the `inputStyle` prop on a DOM element.

### ISSUE THREAD

**Issue by willvlad** [bl00mber/react-phone-input-2#341]
Getting these warnings in the console when using this module:

React does not recognize the `iconStyle` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `iconstyle` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

React does not recognize the `inputStyle` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inputstyle` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Any idea how to get rid of them?

**Comment by r4kh4t** [comment]
Having same problems
