### ISSUE TITLE
Placeholder doesn

### ISSUE THREAD

**Issue by emrys8** [bl00mber/react-phone-input-2#36]

**Comment by emrys8** [comment]
Using the Component this way:
<ReactInput
  placeholder="some placeholder text"
  ...other props
/> 

- The placeholder doesn't seem to show at all

**Comment by bl00mber** [comment]
I can't reproduce this. In all browsers that I use placeholder works. If you are found out why placeholder doesn't show and it will be related to component bugs, feel free to reopen this issue.

**Comment by kshakthi** [comment]
same here
