### ISSUE TITLE
Style props not applied

### ISSUE THREAD

**Issue by gwuah** [bl00mber/react-phone-input-2#369]
When i pass a style prop downwards to the components, my styles don't appear?
Could I be doing something wrong(highly doubt) or it's a bug?

**Comment by gwuah** [comment]
So i just checked the docs again and it seems support for react styling has been added.
when i first used this library about 1year ago,  I had to create my own index.d.ts file even haha
closing this now.

**Comment by puzant** [comment]
Hello 
I'm struggling to change the styles of the input, I've checked the docs over & over but couldn't figure it out 
```
<StyledPhoneInput
      country={'us'}
   />
```

should I pass them as props or is there another way?
