### ISSUE TITLE
Does not work with NextJS due to Next not supporting global CSS files

### ISSUE THREAD

**Issue by UlyssesInvictus** [bl00mber/react-phone-input-2#383]
The current installation for this library recommends direct import of the styles library as a global CSS file.

However, some frameworks like NextJS forbid this methodology, throwing the following error:

```
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
```

(More about this practice in NextJS can be found in [this thread](https://github.com/vercel/next.js/issues/12079)).

Is it possible to update the library so that style is automatically injected into the component? I understand why the styles are exported separately (to support themes), but in our case we cannot use the recommended solution of manually exporting the library styles from `_app.js`.

In my project's particular case, we are resorting to manually copying the styles from this lib and injecting them in our project location, but this is not ideal, so alternate solutions would be helpful. Thank you!

**Comment by bl00mber** [comment]
This practice introduced by NextJS seems like a regression from existing JS standard functionality.
As previous user of NextJS, I remember that it allowed previously to import CSS files at least in older versions.
If it currently forbids importing of CSS modules from NPM folder, I can suggest to use older NextJS versions, move CSS file to another folder, or use examples from the issue in your link.

**Comment by gabrielalmeida** [comment]
What version of NextJS are you using? This should be supported in recent versions, It works for me [importing on `_app` or inside any component directly](https://nextjs.org/docs/basic-features/built-in-css-support#import-styles-from-node_modules). Check if you're above v9.5.4.

Note that this [NextJS feature is broken when using `npm link`](https://github.com/vercel/next.js/issues/19717#issuecomment-761048391), maybe that's your case.

**Comment by UlyssesInvictus** [comment]
Thanks for the help, it turns out that `next-transpile-modules` is actually
the library that's responsible:
https://github.com/martpie/next-transpile-modules/issues/146

We do unfortunately have a hard requirement on using that library though
(and the maintainer is actively looking for a solution as of 10 days ago),
so I suppose I'll just have to try and find a hack.

Although, it does appear that NextJS does break along these lines if you're
on a version prior to 9.5.4 We were able to upgrade past that, so it wasn't
a problem for us, but I know not everyone will be able to.
