### ISSUE TITLE
Component state doesn't allow for resetting input's value

### ISSUE THREAD

**Issue by zukoaang** [bl00mber/react-phone-input-2#40]
Hi,
Seems like there is an issue with the way the state is being handled here.
I use this component in a modal, and I made it so that every time the modal opens, it resets its own state.
So all the inputs in the modal should appear empty once the modal opens.
The problem is that ReactPhoneInput does not.
It gets the `value` prop which is set to `this.state.phone`.
So you would think that once the state resets, and the value of `this.state.phone` is `''`, the input will adjust accordingly.
But in practice, the value inside the input does not change, even though the `value` prop is passing correctly.
I noticed a field in the component's state named `formattedValue`, which seems to always stay the same unless the user types in a different value in the input.
This seems like a bug.

adding example code below
```
     <ReactPhoneInput
          inputStyle={{ width: '100%' }}
          defaultCountry={'us'}
          disableAreaCodes={true}
          enableLongNumbers={true}
          value={this.state.phone}
          placeholder={'phone'}
          onChange={this.setPhone}
     />

  setPhone = phone => {
    this.setState({ phone })
  }

  _clean = () => {
    this.props.resetError()
    this.setState({error: '', name: '', email: '', role: '', phone: ''})
  }

  openModal() {
    this._clean()
    this.modal.open()
  }
```
all the inputs are cleared except for ReactPhoneInput :(

Thanks.

**Comment by bl00mber** [comment]
Please provide repository with the minimal working code.
