### ISSUE TITLE
Ctrl+C not working

### ISSUE THREAD

**Issue by Sayroyten** [bl00mber/react-phone-input-2#403]
Hello, tried in the demo pages
https://bl00mber.github.io/react-phone-input-2.html
https://bl00mber.github.io/react-phone-input-2-css.html

Type a number
Ctrl+A (works)
Ctrl+C (doesnt works)
Ctrl+V (works)

**Comment by Hideman85** [comment]
Same issue here (using firefox)
Works when copyNumbersOnly is set to false (true by default)
Suppose something is wrong with this piece of code:
```
r.handleInputCopy=function(e){if(r.props.copyNumbersOnly){var t=window.getSelection().toString().replace(/[^0-9]+/g,"");e.clipboardData.setData("text/plain",t),e.preventDefault()}}
```
I guess the prevent default there make the copy action canceled

**Comment by bl00mber** [comment]
It works in my browser.
Seems your browser does not support some of the internals of `handleInputCopy`.
You shall use property `copyNumbersOnly=false`.

**Comment by Hideman85** [comment]
"My browser" it is Firefox (78.8.0esr (64-bit) Linux/Debian) not Internet Explorer nor an exotic browser...

I think you should support this feature properly since it is very useful to copy only the number without the formatting.

**Comment by bl00mber** [comment]
I cannot debug your issue without you specifying what exactly isn't working.
As I've said, it works in my browser.

**Comment by Sayroyten** [comment]
well im in firefox 87.0 (64 bits) win10, like most of our users and nobody can copy/paste the numbers :/

**Comment by longprao** [comment]
Same issue here, I cannot copy the phone number input on Firefox (it works on chrome). On FF if I select the text inside the input field, copy then paste, nothing shows up. I only notice this when my clients reported it, so it's a common issue and easy to reproduce.
