### ISSUE TITLE
Cannot enter braces "()" for german phone number

### ISSUE THREAD

**Issue by chtpl** [bl00mber/react-phone-input-2#408]
When I select +49 and then want to continue the number with the city prefix "(0) 30" for Berlin for example, when I press "Shift+8" to add the "(" character, it doesn't get written to the field. How to fix this?

**Comment by NorbertSan** [comment]
You can customize a mask for German, .e.g.:

`<PhoneInput 
     masks={{de : '(.) ... ........'}}
`

I am struggling with setting 0 as default in the brackets but I did not find a solution for that yet

**Comment by chtpl** [comment]
Thanks :) didn't know the masks are separate for every country, that's good :)
