### ISSUE TITLE
Props combination error

### ISSUE THREAD

**Issue by rubenpro** [bl00mber/react-phone-input-2#43]
Hi, when I set defaultCountry prop with another country instead of USA (Japan for example) and no more props, always displays the USA flag.

![reactphoneinput](https://user-images.githubusercontent.com/36886621/45227253-7e771b00-b2c0-11e8-8c9a-6292dc474fa3.png)

But when I open the developer tools, brings me the japan flag...

Any advice?

**Comment by bl00mber** [comment]
Can't reproduce.
