### ISSUE TITLE
+ should be included in value

### ISSUE THREAD

**Issue by ad-si** [bl00mber/react-phone-input-2#432]
If the `value` is supposed to be the correct, dialable phone number, than the `+` must be included. Without the plus, the phone number is not correct and can not be dialed.

**Comment by bl00mber** [comment]
You can handle `+` on your app side if you intend to use value in web calls.

**Comment by omertalmi1** [comment]
@bl00mber Can you add this information to the readme, I think it should be more clear, thanks
