### ISSUE TITLE
Not using base64 URIs for production

### ISSUE THREAD

**Issue by n4gashi** [bl00mber/react-phone-input-2#45]
I'm currently trying to use react-phone-input-2 on a production website where `data:` schemes are not allowed for [security reasons](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src) (see `<scheme-source>` section).

Is that a possible thing for you guys to not use base64 URIs as it is currently insecure and could potentially lead to arbitrary data injection ? I'm willing to do the PR if this is a yes. This should be as simple as removing the `url-loader` from the webpack config.

**Comment by bl00mber** [comment]
How you want to load this data?
Can this feature be configurable (when you turning off base64 data by boolean component prop value)?

**Comment by bl00mber** [comment]
So, this will require additional import? What you mean by manually storing?
By default component should loads by simply `import ReactPhoneInput from 'react-phone-input-2'` without additional imports and base64 strings injections. If this behavior will not be breaked, feel free to send PR.
