### ISSUE TITLE
Set default font-size of text input to 16px

### ISSUE THREAD

**Issue by timukasr** [bl00mber/react-phone-input-2#463]
Mobile Safari has "feature" that when user focuses a field which has font-size less than 16px, browser will zoom in on the text field. This happens with react-phone-input-2 because the default font-size of the input is 14px. Problem can be simply fixed by library user by setting font-size bigger (or using viewport meta tag), but it would make sense for library to offer defaults that work best across different devices.

**Comment by bl00mber** [comment]
14px is a standard font-size on desktop. You can modify style in your app using css selector.
