### ISSUE TITLE
Placeholder value is ignored if country is used

### ISSUE THREAD

**Issue by vivekvardhanadepu** [bl00mber/react-phone-input-2#464]
It would be better if placeholder is still visible next to country code
<img width="316" alt="Screenshot 2021-09-21 at 9 54 11 AM" src="https://user-images.githubusercontent.com/32814044/134111350-726db9c4-8b1e-47cc-aa6d-22000bc24681.png">

**Comment by keanan** [comment]
+1

**Comment by touregeldi** [comment]
+1

**Comment by XxOsirisxX** [comment]
+1

**Comment by hipdev** [comment]
Hi folks, try this: 
```javascript 

  const [value, setValue]= useState('')
  // ...

  useEffect(() => {
    // tricky way of set as empty the phoneInput with a country code selected

    let timer = setTimeout(() => setValue('1'), 100)  // or whatever state you have, Formik, RHF...
    let timer2 = setTimeout(() => setValue(''), 200)
    return () => {
      clearTimeout(timer)
      clearTimeout(timer2)
    }
  }, [])

  // ... add value to your PhoneInput component like always...
```
 Voilà, it works 😉

**Comment by Nick-Dunne** [comment]
> Hi folks, try this:
> 
> ```js
>   const [value, setValue]= useState('')
>   // ...
> 
>   useEffect(() => {
>     // tricky way of set as empty the phoneInput with a country code selected
> 
>     let timer = setTimeout(() => setValue('1'), 100)  // or whatever state you have, Formik, RHF...
>     let timer2 = setTimeout(() => setValue(''), 200)
>     return () => {
>       clearTimeout(timer)
>       clearTimeout(timer2)
>     }
>   }, [])
> 
>   // ... add value to your PhoneInput component like always...
> ```
> 
> Voilà, it works 😉

dont work)
