### ISSUE TITLE
BUG: Country guess should not set previously selected country if it failed to guess the country

### ISSUE THREAD

**Issue by veIiaIiev** [bl00mber/react-phone-input-2#488]
I'll use demo for testing this issue: https://bl00mber.github.io/react-phone-input-2.html

**Steps to reproduce:**

1. Type 7 in the phone input field. It will correctly detect that i'm trying to type russian phone number
2. Remove 7 from the input

**Current behavior:**

Country guess still shows us Russia

**Expected behavior:**

Country guess shows us empty country, because it failed to guess country

**Comment by bl00mber** [comment]
See comment to PR.
