### ISSUE TITLE
Placeholder is always american phone number

### ISSUE THREAD

**Issue by alicerocheman** [bl00mber/react-phone-input-2#494]
Hello

No matter which country is active, placeholder always shows american phone number
Is there any way to have the correct placeholder according to the active country?

Here, france is selected, but placeholder shows an american number:
![Screenshot 2022-02-02 at 09 26 54](https://user-images.githubusercontent.com/21168856/152118699-85746792-2d45-4515-a6ea-5b7224302594.png)

**Comment by alicerocheman** [comment]
Meanwhile, I've been generating my own placeholder, from the country format, if you want to use it in the lib:

```
  const phoneCountryFormat = useMemo(() => phoneCountry?.format || undefined, [phoneCountry]);

  const placeholder = useMemo(() => {
    if (phoneCountryFormat) {
      const words = phoneCountryFormat.split(' ');
      words.shift(); // I'm using only local numbers so here I remove the country code from the format
      let text = words.join(' ');
       // first digit is special on french numbers, these 3 lines could be removed
      if (country === 'fr') {
        text = text.replace('.', '6');
      }
      while (text.indexOf('.') > -1) {
        text = text.replace('.', `${Math.min(9, Math.max(1, Math.floor(Math.random() * 10)))}`);
      }
      return text;
    }
    return '';
  }, [phoneCountryFormat, country]);
```

**Comment by bl00mber** [comment]
Thanks, I will probably add your placeholder code as a guide.

**Comment by Nick-Dunne** [comment]
> ```js
>   const phoneCountryFormat = useMemo(() => phoneCountry?.format || undefined, [phoneCountry]);
> 
>   const placeholder = useMemo(() => {
>     if (phoneCountryFormat) {
>       const words = phoneCountryFormat.split(' ');
>       words.shift(); // I'm using only local numbers so here I remove the country code from the format
>       let text = words.join(' ');
>        // first digit is special on french numbers, these 3 lines could be removed
>       if (country === 'fr') {
>         text = text.replace('.', '6');
>       }
>       while (text.indexOf('.') > -1) {
>         text = text.replace('.', `${Math.min(9, Math.max(1, Math.floor(Math.random() * 10)))}`);
>       }
>       return text;
>     }
>     return '';
>   }, [phoneCountryFormat, country]);
> ```

how it works? 
where to put this code?

**Comment by yungkittty** [comment]
@Nick-Dunne the placeholder memo value should be passed to the input as props
