### ISSUE TITLE
how do I get the CountryData from the countryCode?

### ISSUE THREAD

**Issue by alicerocheman** [bl00mber/react-phone-input-2#495]
Hello,

I havent been able to get placeholders according to the active country (see issue #494) so I'm trying to generate my own from the country format.

It works pretty well. Here's what I did:
```jsx
  const placeholder = useMemo(() => {
    if (phoneCountryFormat) {
      const words = phoneCountryFormat.split(' ');
      words.shift();
      let text = words.join(' ');
      if (country === 'fr') {
        text = text.replace('.', '6');
      }
      while (text.indexOf('.') > -1) {
        text = text.replace('.', `${Math.min(9, Math.max(1, Math.floor(Math.random() * 10)))}`);
      }
      return text;
    }
    return '';
  }, [phoneCountryFormat, phoneCountryDialCode]);
```

Unfortunately, at first, I don't have a CountryData object, which is available only after the first onChange event, so I don't have the format. I do have the active countryCode though, so I'm looking for a way to retrieve the format from the countryCode.

Is there any way to do this?

**Comment by bl00mber** [comment]
Do your PR #484 solves your issue?

**Comment by alicerocheman** [comment]
No it doesn't unfortunately. (I'm using my placeholder)

I found a cheap fix, I call the onChange in onFocus, but it would be better to have the placeholder without the user having to focus on the input. :/

Ideally, I think the lib should export the CountryData array, including the placeholders, so we could use everything directly whenever we want.

**Comment by bl00mber** [comment]
You cannot get CountryData from countryCode because countryCode is iso2 number while CountryData is an internal class.
I close this issue and I will allow CountryData to be modified when lib is initialized.
