### ISSUE TITLE
[bug] disableCountryCode still inserts countryDialCode in input

### ISSUE THREAD

**Issue by alicerocheman** [bl00mber/react-phone-input-2#496]
Hello,

I've passed disableCountryCode as true, but when I switch countries, the new country's code is still inserted into the value.

I tried removing the countryCode by hand in the onChange as documented, but it doesn't work either.

```jsx

  const handleChange = useCallback(
    (value, country, event, formattedValue) => {
      if (onChange) {
        const countryCodeLength = country.dialCode.length;
        let newValue = value.slice(countryCodeLength);
        onChange(newValue, country, event, formattedValue);
      }
    },
    [onChange]
  );

  return <LibPhoneInput
        localization={localization}
        country={country}
        inputProps={{ id }}
        value={value}
        inputClass={computedInputClassName}
        buttonClass={buttonClassName}
        searchPlaceholder={searchPlaceholder}
        searchNotFound={searchNotFound}
        onChange={handleChange}
        disableCountryGuess
        disableCountryCode
        countryCodeEditable={false}
        placeholder={placeholder}
        {...props}
      />
```

the value stored is "" but the country code still appears in the input.

https://user-images.githubusercontent.com/21168856/152140205-8f22568a-9f61-4b2c-97a3-d1100059937c.mov

**Comment by princesust** [comment]
@alicerocheman did you find any way to disable country code?

**Comment by levanchien** [comment]
@alicerocheman Did you find solution ?
I have same issue

**Comment by jamalhassouni** [comment]
@alicerocheman I have the same issue any solution for this?

**Comment by hbsandeepj** [comment]
@alicerocheman I also have the same issue, any solution for this?
