### ISSUE TITLE
Can't turn off autoComplete

### ISSUE THREAD

**Issue by developdeez** [bl00mber/react-phone-input-2#499]
Autocomplete shows in my phone when using react-phone-input-2

This dropdown can sometimes cover the input.

Can this be hidden like other inputs? Can it be added?

**Comment by datdang2412** [comment]
Same here.

**Comment by KeerthiHarish** [comment]
This might help you.

```
<PhoneInput
  inputProps={{
    autoComplete: "off"
  }}
/>
```

**Comment by developdeez** [comment]
I removed this package. Problem solved
