### ISSUE TITLE
Adding more countries

### ISSUE THREAD

**Issue by semreg** [bl00mber/react-phone-input-2#501]
Hi! I love this lib, however, some countries such as the Cayman Islands (+1345), Niue (+683), Faroe Islands (+296), etc. are missing. I can do PR to add some more countries. Would that be OK?

**Comment by bl00mber** [comment]
It is not countries. Read instruction

**Comment by semreg** [comment]
Yep, I know, I mean codes in general

**Comment by bl00mber** [comment]
It has those codes

**Comment by kishansoftyoi** [comment]
I don't know if something changed after, but I also need those codes, but they are unavailable. It would be cool if we could get those codes.
