### ISSUE TITLE
Add new Country

### ISSUE THREAD

**Issue by Xusrav01** [bl00mber/react-phone-input-2#508]
Please add new country Cayman Island code is +1345

![image](https://user-images.githubusercontent.com/71163361/158015263-c4a76e57-00b0-4c0c-b33a-5c4af6f0244a.png)

**Comment by NathanQ** [comment]
Cayman is listed in [rawTerritories](https://github.com/bl00mber/react-phone-input-2/blob/master/src/rawTerritories.js#L45) 
 and can be enabled with `enableTerritories={true}`

**Comment by Xusrav01** [comment]
Thanks it's work
