### ISSUE TITLE
preferredCountries set to 'us' display all areacodes in dropdown

### ISSUE THREAD

**Issue by mustik22** [bl00mber/react-phone-input-2#51]
Firstly, thank you for creating this excellent product.

I am having an issue with the preferredCountries feature, where it is displaying all of the area code sin the drop down. It would be desirable to have a single entry of +1 rather than all the of the area code values.

preferredCountries="us"

<ReactPhoneInput 
                defaultCountry={ this.props.defaultCountry ? this.props.defaultCountry : "us" }
                preferredCountries={ this.props.preferredCountries } 
...

<img width="387" alt="image" src="https://user-images.githubusercontent.com/27729947/47886719-2ec15580-de12-11e8-959a-16e401b15f32.png">

Any help would be greatly appreciated

**Comment by bl00mber** [comment]
You should read readme.md first

**Comment by mustik22** [comment]
Thank you!

The disableAreaCodes={true} option looks like it will do the trick.  It was unclear from the documentation that the option only applied to the dropdown (so I disregarded it), my error.
