### ISSUE TITLE
get raw value

### ISSUE THREAD

**Issue by Lurtt** [bl00mber/react-phone-input-2#52]
not sure if it is possible but would be gr8 if there could be the way to get `raw value`

for example from number `+1 (111) 234-55545` return `23455545` as a raw value without prefix

**Comment by anhpham1509** [comment]
I would like to extend this ticket a bit.

Could we get the country code out of the phone number?

Also, it's would be great if this is in `onChange` callback.

**Comment by anhpham1509** [comment]
Actually I found the answer for my question.
![screen shot 2018-12-13 at 12 58 54](https://user-images.githubusercontent.com/9955754/49934406-f4e67300-fed6-11e8-9f7e-81bdd7fe2a40.png)

**Comment by anhpham1509** [comment]
Anw, @Lurtt I used this code to get the raw value:
```js
const rawValue = value.match(/(\d|\+)+/g).join('');
```

**Comment by bl00mber** [comment]
https://github.com/bl00mber/react-phone-input-2#phone-without-dialcode
