### ISSUE TITLE
Default value and validation

### ISSUE THREAD

**Issue by UndercoverNL** [bl00mber/react-phone-input-2#555]
So I am struggling a bit with the field properties after I completed the custom CSS. Firstly, Is there a way to set a default value as phone number, I tried it with

`inputProps={{
    value: `+${phone}`,
}}`

Which did work, but it removed the formatting per country, which removed the () and spaces.

And secondly, is there any way to validate the PhoneInput value in a `formik`? And what are the default validations used, since I believe there are some, but they never get triggered, or are there no default validations?

I would like to know those 2 things since then this would be the perfect phone input.

Thanks in advance!

**Comment by kumaranubhaw** [comment]
@UndercoverNL Yes you can give `default value` to PhoneInput and validate using `formik`.
As you are using `formik` you can just assign value to the PhoneInput

Below is the react format code:

While setting initial value set the default phone number with country code:
here 1 at the 1st in the phoneWithDialCode is country code

> initialValues: {
>   phoneWithDialCode: '13849503845',
>   countryCode: '',
>   phone: ''
> }


> <PhoneInput
>     inputProps={{
>       name: 'phone',
>     }}
>     country={'us'}
>     placeholder=""
>     onChange={(value, data) => {
>       handlePhoneInput(value, data);
>     }}
>     value={formik.values.phoneWithDialCode}
>   />

handle phone input on change:

>   const handlePhoneInput = (value, data) => {
>     formik.setFieldValue('phoneWithDialCode', value);
>     formik.setFieldValue('countryCode', '+' + data.dialCode);
>     formik.setFieldValue('phone', value.slice(data.dialCode.length));
>   }

validate phone number in validation of formik:

> if(values.phone && values.phone.length !== 10) {
>   errors.phone = 'Enter valid 10 digits phone number';
> }
> 

Here is how you can display error message in div tag:

>     {formik.touched.phone && formik.errors.phone
>       ? formik.errors.phone
>       : ''}

**Comment by UndercoverNL** [comment]
thanks @kumaranubhaw I will try that!

**Comment by UndercoverNL** [comment]
the:
`inputProps={{
    name: 'phone',
}}`

Didn't do anything in the end, like I also tested before your reply, sadly enough it doesn't allow you to get the value from the formik submit even, so you will still need to make us e of the `onChange`  event with an `useState`. However, the `value={values.phone} did work  as default value including the formatting, thanks!

The validation also works if you save the country code and phone number separately from each other.

thanks for your help, all works now.
