### ISSUE TITLE
Appearance none for default select

### ISSUE THREAD

**Issue by nalnir** [bl00mber/react-phone-input-2#571]
Is it possible to hide the default dropdown arrow for the select? 
I tried to use `{{'appearance': 'none'}}` for all styles but it didn't work.
I also use tailwind css and tried if it works for the component and padding or opacity works well, but not appearance-none when I tried something like this `dropdownClass='appearance-none'`

**Comment by D3press3dd** [comment]
Hi, you can create a css stylesheet and add this class
`.react-tel-input .selected-flag .arrow {
display:none;
}`
and it's gone as you can see in the image below, hope this works for you, let me know anything
![image](https://user-images.githubusercontent.com/79771334/188951723-78d772e8-7426-4efc-906b-2948b1c7c68f.png)

**Comment by nalnir** [comment]
Awesome, thank you, works like magic :)

**Comment by D3press3dd** [comment]
no problem, you're welcome
