### ISSUE TITLE
Element type is invalid

### ISSUE THREAD

**Issue by wedomendixapps** [bl00mber/react-phone-input-2#595]
Hi

I encounter following issue:
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

I've used only following code:
<PhoneInput
        value={phoneNumberAttribute.displayValue  === '' ? undefined : phoneNumberAttribute.displayValue }
        onChange={(value?: string) => {
            phoneNumberAttribute.setValue(value);
        }}
        disabled={false}
        placeholder="Place holder"/>

**Comment by wedomendixapps** [comment]
I've changed input like this
var PhoneInput = require('react-phone-input-2').default

**Comment by army003** [comment]
Hi, could you please show, where you add this line? => var PhoneInput = require('react-phone-input-2').default
