### ISSUE TITLE
Got an 'Element type is invalid:expected a string or a class/function but got :object' error

### ISSUE THREAD

**Issue by army003** [bl00mber/react-phone-input-2#598]
![image](https://user-images.githubusercontent.com/92534302/211788598-c9c093e4-3ab9-40c5-bf79-e48933e7fcb1.png)

When i do everything locally, everything works well, but when i'm trying ro upload changes on development environment, i got this error

My component 

<PhoneInput
        control={control}
        id={name}
        name={name}
        localization={ru}
        country={'kz'}
        value={phone}
        inputProps={{
          name: name,
          required: true,
          autoFocus: false
        }}
        placeholder={''}
        regions={['ex-ussr']}
    
        onChange={onChangeHandler}
        areaCodes={{ kz: ['7'] }}
        isValid={(value, country) => {
          return checkValid(value, country);
        }}
      />

**Comment by gpavlov21** [comment]
I'm having the same issue. Everything working fine locally, but when i build and deploy it breaks. Did you manage to fix it @army003 ?

**Comment by army003** [comment]
@gpavlov21 yes, i fixed. I had this error because i am using the Vte. I just add this => const CountryPhoneInput = PhoneInput.default ? PhoneInput.default : PhoneInput;
![image](https://github.com/bl00mber/react-phone-input-2/assets/92534302/97c2f989-09ae-4659-a3f6-aa02b2ad4f5f)
![image](https://github.com/bl00mber/react-phone-input-2/assets/92534302/d473049c-a7fa-4969-be5c-732a477b2e64)
