### ISSUE TITLE
Country prefix missing when value set to empty string

### ISSUE THREAD

**Issue by Criezc** [bl00mber/react-phone-input-2#637]
Hi, currently I'm using your libraries as phone number input. But I encountered an issues where if I click the reset button which resetting the value of `sender` into an empty string. It forces the country prefix (+62) into null. Only leaving the flag it self

this is my code
```jsx
<InputPhone
                        label="Sender Number"
                        value={sender}
                        onChange={setSender}
                        country="id"
                        onlyCountries={['id']}
                      />
```
                      
for the examples after I set my sender state into empty string
    
![image](https://github.com/bl00mber/react-phone-input-2/assets/68372390/802868f5-68ac-4aa8-bd19-546d737430b8)

**Comment by Criezc** [comment]
issues resolved by setting setState into `('+62')`

**Comment by madCodes** [comment]
Im not sure why is this closed. This is a genuine issue and becomes more prominent when we use "countryCodeEditable" false. Once we reset, we cannot input anything even though country flag is visible  until we change the country dropdown. Very confusing to the user. :(

**Comment by ravi-roxiler** [comment]
Yes,facing same issue any update on this??


> Im not sure why is this closed. This is a genuine issue and becomes more prominent when we use "countryCodeEditable" false. Once we reset, we cannot input anything even though country flag is visible until we change the country dropdown. Very confusing to the user. :(
