### ISSUE TITLE
When defaultCountry from prop changes, component doesn't update.

### ISSUE THREAD

**Issue by schocior** [bl00mber/react-phone-input-2#70]
I have a drop down with country codes, when selecting one and passing it to default country prop the component does not update with the correct default country. I have investigated the problem and it looks like the `setState` from `updateDefaultCountry` it is overwritten by the `setState` from `updateFormattedNumber`, I have tried to call `updateFormattedNumber` after `setState` from `updateDefaultCountry` has finished and it works like expected. The functions that I am referring to are:

` updateDefaultCountry = (country) => {
    const newSelectedCountry = find(this.state.onlyCountries, {iso2: country});
    this.setState({
      defaultCountry: country,
      selectedCountry: newSelectedCountry,
      formattedNumber: this.props.disableCountryCode ? '' : '+' + newSelectedCountry.dialCode
    });
  }

  updateFormattedNumber(number) {
    const { onlyCountries, defaultCountry } = this.state;
    let countryGuess;
    let inputNumber = number;
    let formattedNumber = number;

    // if inputNumber does not start with '+', then use default country's dialing prefix,
    // otherwise use logic for finding country based on country prefix.
    if (!inputNumber.startsWith('+')) {
      countryGuess = find(onlyCountries, {iso2: defaultCountry});
      const dialCode = countryGuess && !startsWith(inputNumber.replace(/\D/g, ''), countryGuess.dialCode) ? countryGuess.dialCode : '';
      formattedNumber = this.formatNumber(
        (this.props.disableCountryCode ? '' : dialCode) + inputNumber.replace(/\D/g, ''),
        countryGuess ? countryGuess.format : undefined
      );
    }
    else {
      inputNumber = inputNumber.replace(/\D/g, '');
      countryGuess = this.guessSelectedCountry(inputNumber.substring(0, 6), onlyCountries, defaultCountry);
      formattedNumber = this.formatNumber(inputNumber, countryGuess.format);
    }

    this.setState({ selectedCountry: countryGuess, formattedNumber });
  }`

And are called from here: 

`componentWillReceiveProps(nextProps) {
    if (nextProps.defaultCountry && nextProps.defaultCountry !== this.state.defaultCountry) {
      this.updateDefaultCountry(nextProps.defaultCountry);
    }
    if (nextProps.value !== this.state.formattedNumber) {
      this.updateFormattedNumber(nextProps.value);
    }
  }`

**Comment by michaeljamie** [comment]
Also having this same issue.  Would be nice to have a fix included that updates the country code based off of the default country.

**Comment by bl00mber** [comment]
This is the initial value. For non-initial value use `value` prop.

**Comment by bl00mber** [comment]
Maybe will add this in the future because apps can have dynamic UI scenarios.
