### ISSUE TITLE
Does not always differentiate between USA and Canada

### ISSUE THREAD

**Issue by jean343** [bl00mber/react-phone-input-2#72]
Let's say I enter a phone number in Canada/Quebec `+1 (450) 000-0000`.

When guessing the country, it only looks at the first 5 characters including space and brackets `1 (45`.
![image](https://user-images.githubusercontent.com/7070881/51434389-52d04e00-1c2d-11e9-9120-e3fd74a31706.png)

This is not enough data as it needs `1450` to guess the correct country.

Thanks

**Comment by bl00mber** [comment]
This was probably another bug. Value that passed into that function is already without braces.
