### ISSUE TITLE
[bug] input should use style={{direction: "ltr"}} to work well in RTL languages/layouts

### ISSUE THREAD

**Issue by ceefour** [bl00mber/react-phone-input-2#73]
In RTL language.layout, ReactPhoneInput becomes RTL, which does not work well:

![image](https://user-images.githubusercontent.com/24123/51535326-b4d1c300-1e7a-11e9-9bd1-062905fe9fd8.png)

As a phone input is always LTR regardless of language, please use `style={{direction: "ltr"}}`

Note: setting `inputStyle=` doesn't seem to work.

**Comment by bl00mber** [comment]
So, you basically want to use this direction by default? This is not a bug, but a correct behavior. If you want to add extra props, use `inputExtraProps`.

**Comment by ceefour** [comment]
@bl00mber shouldn't it be `inputStyle`? I noticed when got hit by this bug, setting `inputStyle={{direction: 'ltr'}}` has no effect, is it a bug?

**Comment by bl00mber** [comment]
I already have written above. No, it shouldn't been `inputStyle`.
