### ISSUE TITLE
The defaultCountry props for Kazakhstan does not work correctly.

### ISSUE THREAD

**Issue by IrinaZorkova** [bl00mber/react-phone-input-2#75]
The country code of Kazakhstan is the same as the code of Russia (+7).  
When I start to enter in the field in which the defaultCountry = 'kz', the input mask and flag switches to Russia.
Thank you.

**Comment by bl00mber** [comment]
So, how you expect to make me this work if the input is the same?

**Comment by bl00mber** [comment]
#49
