### ISSUE TITLE
Not able to reset the phone number

### ISSUE THREAD

**Issue by idanwe** [bl00mber/react-phone-input-2#8]
I need to reset the phone input after submitting change user phone number phone, and I can't do it.

I look for what is different that the initial props and I saw [in this line](https://github.com/bl00mber/react-phone-input-2/blob/master/src/index.js#L157), that due to the check that `nextProps.value` is defined trying to reset it with `'' ` doesn't change the input formatted value. 

Is it intentional? It need to prevent some scenario? Can I submit a PR to change this behavior?

In the meantime I change the value to '+' and it works partially, due that I don't have the default country code any more.

**Comment by bl00mber** [comment]
You can sent PR if you want to remove `nextProps.value` check or I might remove this later.
