### ISSUE TITLE
Including this library causes test environment failures

### ISSUE THREAD

**Issue by NoiSek** [bl00mber/react-phone-input-2#81]
Any component that includes this library is currently untestable due to the definition of `global` here:
https://github.com/bl00mber/react-phone-input-2/blob/master/src/global.js#L1

I'm not sure what purpose this line is supposed to serve, but it doesn't seem to work as expected and overrides any definition of global that has already been defined.

What prevents this entire file from being simplified to the below?

```
export const document = (global && global.document) || {};
```

**Comment by bl00mber** [comment]
#14
