### ISSUE TITLE
Auto focus issues

### ISSUE THREAD

**Issue by duongkhoangiam** [bl00mber/react-phone-input-2#83]
index.js:1 Warning: Received the string `true` for the boolean attribute `autoFocus`. Although this works, it will not work as expected if you pass the string "false". Did you mean autoFocus={true}?

**Comment by bl00mber** [comment]
#66

**Comment by dalalRohit** [comment]
hope this helps ;)

[https://github.com/bl00mber/react-phone-input-2/issues/292#issuecomment-1231211374](https://github.com/bl00mber/react-phone-input-2/issues/292#issuecomment-1231211374)
