### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by Richtervn** [bl00mber/react-phone-input-2#87]
ReferenceError: window is not defined
    at Object.<anonymous> (D:\Projects\co-invest\client\node_modules\react-phone-input-2\dist\index.js:1:258)

I tried to use it with nextjs and got this problem. Will you support server side rendering ?

**Comment by bl00mber** [comment]
I'll try to debug ssr in the next few weeks.

**Comment by isuvorov** [comment]
Hello! We really liked your plugin, but we use server rendering and "window" crash our app. If you don't have a time, could we help you?

**Comment by bl00mber** [comment]
https://github.com/markdalgleish/static-site-generator-webpack-plugin/issues/130
