### ISSUE TITLE
Feature Request: Add option to add custom component for search field

### ISSUE THREAD

**Issue by kaung8khant** [bl00mber/react-phone-input-2#91]
Would be nice to add custom component instead of having only class option for search field. It would be useful for those who has design standard and structure.

For example, icon  &#128270;  `&#128270;` is added to the code statically and there's no way to change it.

**Comment by bl00mber** [comment]
I have added an option to disable search icon. Also you can hide/modify this icon using css.

**Comment by dkrefta** [comment]
hey guys, I was looking for changing the Icon, but the lib only has the disable for that, there is a way to insert an SVG there? thanks
