### ISSUE TITLE
Phone Number Validation

### ISSUE THREAD

**Issue by JohnPochta** [bl00mber/react-phone-input-2#92]
Hi, dear, developer! 
I'm wondering how i can get boolean validation result for the inputted value in onChange(value, countryProps) handler ?
For example, for some countries I can't input more that 12 digits, cuz your component doesn't allow it to me, cuz standart for that countries it's not 9, not 10, but EXACTLY 12 digits. And if i'll input 8 digits phone number for them - your component won't let me know that current number is incorrect.  Why it doesn't return to me boolean value "isCorrect", which will let me know is currentValue - it's  a correct phone number for chosen country? Can you add this?

**Comment by fatlinesofcode** [comment]
Using a ref, you can compare the the length of the selected country phone format from the state against the input number e.g.

```
<ReactPhoneInput defaultCountry={'au'} enableLongNumbers={false} disableAreaCodes={true}
                     preferredCountries={['au', 'us']}
                     value={input.value}
                     onChange={onChange}
                     isValid={ (value) => {
                       if(this.phoneInput){
                         const {selectedCountry : {format, dialCode}, formattedNumber} = this.phoneInput.state
                         return format.length === formattedNumber.length
                       }
                     }}
                     ref={ node => this.phoneInput = node}
```

**Comment by yashshukla1912** [comment]
Even i am facing same issue, can u please share an example of validating a mobile number based on country.

**Comment by raphaelnoguier** [comment]
Hey,

You can see if the number is valid by using this : 

`isValid={val => {
	if (phoneInput) {
	      const { selectedCountry: { format, dialCode }, formattedNumber } = phoneInput.state;
	      const condition = format.length === formattedNumber.length && val.startsWith(dialCode);
	      console.log(condition);
	      return condition;
	}
}}` 

On my console i get false every times i type and when i get the correct number length, the condition is set to true. This is perfect. 

But here is my problem : for some reasons when my condition change to true the input value is cleared.

@bl00mber have you any idea ? 

Thanks :)

**Comment by raphaelnoguier** [comment]
Hey @bl00mber, after thinking about it, i think that when isValid change, the input is Re-rendered. And as my value is empty by default, and nothing update this value, the field takes the initial value "".

Am i right ?

**Comment by naveennazimudeen** [comment]
I took this approach to validate the length of phoneInput and it seems to work:

```
   const [phone, setPhone] = useState('')
   const [selCountryExpectedLength, setSelCountryExpectedLength] = useState(0)
   const [isValid, setIsValid] = useState(true)

   <PhoneInput 
        country={'us'} 
        value={phone} 
        countryCodeEditable={false} 
        enableSearch={true}
        placeholder=""
        onChange={(inputPhone, countryData) => {
          setPhone(inputPhone);
          setSelCountryExpectedLength(countryData.format.replace(/[^.]/g, '').length)
        }}
        onBlur={()=>{
          if(phone.replace(/\D/g, '').length != selCountryExpectedLength){
            setIsValid(false)
          }else{
            setIsValid(true)
          }
        }}
        isValid={() => !isValid ? phone.replace(/\D/g, '').length == selCountryExpectedLength : isValid}
    />
```

**Comment by bl00mber** [comment]
I suggest to continue discussion in #204

**Comment by kishansoftyoi** [comment]
> Using a ref, you can compare the the length of the selected country phone format from the state against the input number e.g.
> 
> ```
> <ReactPhoneInput defaultCountry={'au'} enableLongNumbers={false} disableAreaCodes={true}
>                      preferredCountries={['au', 'us']}
>                      value={input.value}
>                      onChange={onChange}
>                      isValid={ (value) => {
>                        if(this.phoneInput){
>                          const {selectedCountry : {format, dialCode}, formattedNumber} = this.phoneInput.state
>                          return format.length === formattedNumber.length
>                        }
>                      }}
>                      ref={ node => this.phoneInput = node}
> ```

@fatlinesofcode I tried this approach but there is one issue for the country "Bolivia"  (this is only one example there could be many)
format: "+... ... ... ... ... .."
As you can see it has 14 length without considering the dialer code and spaces but "Bolivia" has 8 length (without dialer code and spaces) of valid mobile numbers. so in this case this solution will not work
