### ISSUE TITLE
Flag dropdown empty/not showing

### ISSUE THREAD

**Issue by jeffreyabarrios** [bl00mber/react-phone-input-2#95]
Two things, the stylesheet throws an error when importing 'Failed to compile. You may need an appropriate loader to handle this file type'. And the other thing is that the dropdown never shows.

Here's the way I used the component with the latest release "react-phone-input-2": "^2.9.3"

```
import ReactPhoneInput from 'react-phone-input-2';

....
....

<ReactPhoneInput defaultCountry={'gt'} disableDropdown={false}  value={this.state.phoneValue} onChange={e => console.log(e)}/>
```

And even passing the prop regions, the dropdown does not appears and when inspecting the component, it's just the  flag-dropdown container with the arrow inside and nothing more. Any solution?

I'm using  "react": "^16.8.1" and "@babel/core": "^7.3.4".

**Comment by bl00mber** [comment]
The bug is in your app, not in the component. You need to import styles and an appropriate loader to handle. Anyway, I will probably change the importing method again to the direct javascript injection to avoid CSS import with external file (I changed importing method and placed styles in different file because of SSR issues), so if you are not using SSR you can use `2.8.0` version.

**Comment by jeffreyabarrios** [comment]
In fact I am using Next for SSR. Leaving beside the styles, all the countries info/flags etc are not showing, no only in style I mean, but the container is just empty. Any help with that?

**Comment by bl00mber** [comment]
That's because styles are required for dropdown to work.

**Comment by jonchaney** [comment]
I am experiencing this same problem on version 2.8.0. I do not think this is a problem with my code as it worked and with no code change on my end it stopped working. Same exact issue with styles no longer showing up for dropdown menu.

**Comment by jonchaney** [comment]
@jeffreyabarrios i uninstalled my node_modules and changed the version to "2.8.0" instead of "^2.8.0" and the problem went away..

**Comment by arpiantonyan** [comment]
I had this issue for more than a week. What worked for me was changing the import 'react-phone-input-2/lib/style.css' to 'react-phone-input-2/lib/plain.css'. Find the package folder in your project and in the 'lib' folder you'll find several .css files, such as 'semantic-ui.css', 'material.css', etc. However, only the 'plain.css' is working although the flag image quality is not the best.
