### ISSUE TITLE
onChange handler should accept standard javascript event object instead of just value

### ISSUE THREAD

**Issue by dnknitro** [bl00mber/react-phone-input-2#96]
Subj.

**Comment by Dagim12** [comment]
Yes, I've been trying to get event object but there is no way to get it.

**Comment by benlieb** [comment]
Me too, this is awful.

**Comment by benlieb** [comment]
The event object has valuable information on it including target and data attributes. Not at least sending the event as a supplemental argument is more limiting that need be. It's disappointing that this was closed without comment.

**Comment by bl00mber** [comment]
> It's disappointing that this was closed without comment.
@benlieb I closed it with a comment...
