### ISSUE TITLE
Check if the number format is correct or not?

### ISSUE THREAD

**Issue by sasankm** [bl00mber/react-phone-input-2#97]
Is there any way to check if the particular phone number entered for a specific country is valid or not?

**Example:** As US phone number consists of 10 digits (excluding the +1 in the beginning), if the user enters 9 digits it stills accepts it!
So, Is there any way to display error or notify them to enter the correct number of digits?

**Comment by dipta007** [comment]
Any update here?

**Comment by bl00mber** [comment]
https://github.com/bl00mber/react-phone-input-2#check-validity-of-the-phone-number
