### ISSUE TITLE
Container style does not work

### ISSUE THREAD

**Issue by LeoMoonStar** [bl00mber/react-phone-input-2#99]
i tried to adjust container width and height, but it does not work

**Comment by LothaireLaeuffer** [comment]
It works for me ! I can set the width of the container with containerStyle. What you might need to do is set inputStyle width to 100%, so that the input will take all the space available in in the container div. Hope it's helping !

**Comment by alessandromontividiu03** [comment]
I worked for me after adding the css file
`import 'react-phone-input-2/dist/style.css'`
